### PR TITLE
skip read only files

### PR DESCRIPTION
**Pull request by cjbd**
for #1401

this change added a new private function `_is_writable` to check file write permission, and update `should_domain_substitute` function to check `_is_writable` first before other validations, if file is read only, return False

### CODE REVIEW

**Review by Eloston — CHANGES_REQUESTED** [review]
Technically this only checks if the file owner has write permissions, not whether the user executing this Python program (`update_lists.py`) has permission to write to the file. See Python docs: https://docs.python.org/3/library/stat.html?highlight=stat#stat.S_IWRITE. A better method is to use [`os.access`](https://docs.python.org/3/library/os.html#os.access). Arguably, the best method is to attempt to domain substitute and abort or skip if an error occurs.

However, I wonder if skipping read-only files is the correct action here. Wouldn't it be safer to update the permissions of the files so domain substitution can work? What is the upside of skipping read-only files?

**Comment by cjbd** [comment]
@Eloston, i guess there're many differences between using downloaded and extracted source files and git cloned source files
i haven't thought all the way through, i only looked at bunch of read only files on my drive, they seems to have nothing to do with source code, i haven't fully tested it yet
you're right, there may be read only files that need to do domain substitution too

**Comment by cjbd** [comment]
i used script to pull all read only files for chromium repo, file attached, it seems ok to skip those, but i'm not 100% sure

[read_only.zip](https://github.com/Eloston/ungoogled-chromium/files/6081218/read_only.zip)

**Comment by Ahrotahn** [comment]
Skipping files could possibly leave you in a situation where your build is not really ungoogled.  
I'm surprised that 43fbd1d76cda2367dbb869e4984ada276833cf5e doesn't work for you.  Does the user you're running the build under have the authority to change those file's permissions?

**Comment by cjbd** [comment]
@Ahrotahn , i don't know why, i got below error message, which points to `with path.open('r+b') as input_file:`

```
Traceback (most recent call last):
  File "./utils/domain_substitution.py", line 399, in <module>
    main()
  File "./utils/domain_substitution.py", line 395, in main
    args.callback(args)
  File "./utils/domain_substitution.py", line 349, in _callback
    apply_substitution(args.regex, args.files, args.directory, args.cache)
  File "./utils/domain_substitution.py", line 261, in apply_substitution
    crc32_hash, orig_content = _substitute_path(path, regex_pairs)
  File "./utils/domain_substitution.py", line 91, in _substitute_path
    with path.open('r+b') as input_file:
  File "/usr/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/path/tochromium/src/third_party/android_sdk/public/build-tools/30.0.1/NOTICE.txt'
```

**Comment by Ahrotahn** [comment]
Are you able to run `chmod +w /path/tochromium/src/third_party/android_sdk/public/build-tools/30.0.1/NOTICE.txt`?

It's possible some part of that path is not owned by your user, or you don't have executable permission on one of the directories in the path.

**Comment by cjbd** [comment]
@Ahrotahn , the file is owned by me, this is probably set by `git` or `gclient sync` to readonly
i'm thinking for chromium&chromiumos source code cloned using official method, have to go for a different way for domain substitution

Screenshot from 2021-03-06 12-21-43

**Comment by Ahrotahn** [comment]
Would you mind running `namei -l /path/tochromium/src/` and posing the output?

**Comment by cjbd** [comment]
@Ahrotahn 
```
f: .
drwxr-xr-x pi pi .
```

**Comment by Ahrotahn** [comment]
You'll need to use the full path to your source directory to get any meaningful results.

**Comment by cjbd** [comment]
@Ahrotahn , thanks for the update, i was busy with other stuff, i scanned both chromium&chromiumos source to extract domains, it's in discussion

@Eloston i don't think this PR is needed for this project, i'm closing it
as for repo cloned using git and gclient, there're many differences, this project already covered download source tar, no need for this change

**Pull request closed without merging**
