### PR TITLE
Update to Chromium 92.0.4515.159

### PR DESCRIPTION
**Pull request by Zoraver**
Addresses #1607. I will let you know once I have a successful build.

Note that quilt seems to have inserted some random spaces at the end of various lines in `remove-unused-preferences-fields.patch`. I do not know why this is occurring, but am not bothered by it enough to manually edit the patch to remove them.

### CODE REVIEW

**Comment by Ahrotahn** [comment]
Builds and runs fine on my end, thanks Zoraver!

**Comment by networkException** [comment]
Works fine for me as well

**Comment by Zoraver** [comment]
My build succeeded and is running well.

Ahrotahn, no problem. Thank you and networkException for testing.

**Comment by PF4Public** [comment]
@Eloston Please give Zoraver and Ahrotahn permissions to merge PRs into this repository.

**Comment by networkException** [comment]
possibly releases as well, at least thats how arch packaging usually references versions

**Comment by wchen342** [comment]
> @Eloston Please give Zoraver and Ahrotahn permissions to merge PRs into this repository.

Yes, I think that will be good. I was actually making a fork so I can adapt new versions quicker.

**Comment by PF4Public** [comment]
> > @Eloston Please give Zoraver and Ahrotahn permissions to merge PRs into this repository.
> 
> Yes, I think that will be good. I was actually making a fork so I can adapt new versions quicker.

Exactly! For one thing to avoid fragmentation! Due to long delays I had to give up following releases of this repository, instead I now mostly use commit-ids for Gentoo: [ungoogled-chromium-92.0.4515.159-r1.ebuild#L17](https://github.com/PF4Public/gentoo-overlay/blob/07e8f442eb4595c8048eae93d016e60cbe05fbfe/www-client/ungoogled-chromium/ungoogled-chromium-92.0.4515.159-r1.ebuild#L17).

**Review by Eloston — APPROVED** [review]

**Comment by Eloston** [comment]
> @Eloston Please give Zoraver and Ahrotahn permissions to merge PRs into this repository.

@Zoraver and @Ahrotahn: Is this something you'd be interested in?

**Comment by Extev** [comment]
So isn't the fix for #1590 available with this version?

**Comment by BachoSeven** [comment]
@Extev I just installed the latest version, and it does not include any of the patches for tabsearch and qr code generation removal, so I suppose it also does not contain the ClearDataOnExit one you're referring to(not convinced enough to test it on my profile tho)

**Comment by Extev** [comment]
@BachoSeven yes, I suppose it's because the PRs for all these patches have been merged after #1608 . I'm afraid we'll have to wait for the next release.

**Comment by PF4Public** [comment]
@extev @bachoseven same happened to #1564. You may apply that PR as patch on your local copy before compiling to have those flags.

**Comment by Ahrotahn** [comment]
> > @Eloston Please give Zoraver and Ahrotahn permissions to merge PRs into this repository.
> 
> @Zoraver and @Ahrotahn: Is this something you'd be interested in?

That's fine with me, I don't mind helping out with merges.  I wouldn't feel comfortable without input from either of you for most changes, but it should hopefully make things easier on you when it comes to small updates like this one.

**Comment by PF4Public** [comment]
I believe help is especially important, since [Chrome is planning to migrate from its current six week release cycle to a new four week release cycle in Q3 2021](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/process/release_cycle_new.md)

I might ultimately suggest myself as a helper, but not until I could allocate some more time, which is not the case at present unfortunately.

**Comment by wchen342** [comment]
@PF4Public @Ahrotahn @Zoraver 
I think a new building method and documentations abount building shall be top priority at this point. I have an (unfinished) python script underway to automatic the whole `checkout` -> `sync` -> `build` thing, inspired by [Brave's `npm` scripts](https://github.com/brave/brave-browser#build-brave). If any of you think this is worth the effort and willing to help I can create a repo for it.

**Comment by wchen342** [comment]
@PF4Public I make a repo for building script: https://github.com/wchen342/ungoogled-chromium-building-scripts.

It's currently half-baked and based on my Android version since I am more familiar with that, but I think it shall mostly work for Linux too. Anyone interested can have a look and improve it.

**Comment by Zoraver** [comment]
> > @Eloston Please give Zoraver and Ahrotahn permissions to merge PRs into this repository.
> 
> @Zoraver and @Ahrotahn: Is this something you'd be interested in?

I am interested in this, but I have to consider the perspective of the people who use this repository because they trust you, rather than myself or Ahrotahn. If you do decide to go forward with this, perhaps you could set it up such that GitHub enforces that pull requests require at least two trusted reviewers to sign-off on them before they are allowed to be merged. Of course, you would still hold the ability to merge any pull request you see fit.

**Comment by Zoraver** [comment]
> > @Eloston Please give Zoraver and Ahrotahn permissions to merge PRs into this repository.
> 
> @Zoraver and @Ahrotahn: Is this something you'd be interested in?

I am interested in this, but I have to consider the perspective of the people who use this repository because they trust you, rather than myself or Ahrotahn. If you do decide to go forward with this, perhaps you could set it up such that GitHub enforces that pull requests require at least two trusted reviewers to sign-off on them before they are allowed to be merged. Of course, you would still hold the ability to merge any pull request you see fit.

**Comment by Eloston** [comment]
@Ahrotahn @Zoraver I have invited you two as collaborators on this repository (considered a personal repository, [see details on permissions here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository#collaborator-access-for-a-repository-owned-by-a-user-account)). I've also enabled a branch protection rule requiring 2+ approvals in PRs, so that means you guys will have to push everything as a PR and get approvals to make changes in this repo. Also, I require approvals from code owners, and I've made you two code owners for all files except a few select files (see `CODEOWNERS` file I pushed to the root for details).

Let me know how this goes. If we need more granular permission control, I may have to move this repo to the ungoogled-software organization and setup a team.

**Comment by PF4Public** [comment]
> I have to consider the perspective of the people who use this repository because they trust you, rather than myself or Ahrotahn.

@Ahrotahn @Zoraver Lets [face it](https://github.com/Eloston/ungoogled-chromium/graphs/contributors): for the last year or so, you both have been steering the whole thing with some comments on improvements from Eloston! All of your commits were merged, which by proxy means, that Eloston must have been trusting your contributions!

**Pull request merged**
