### PR TITLE
Update for 70

### PR DESCRIPTION
**Pull request by xsmile**
### Patches
- removed `patches/iridium-browser/safe_browsing-support-trk-prefix.patch`:
The safebrowsing protocol was updated from v3 to v4 and the relevant code was likely moved to `components/safe_browsing/db/`

### Features
- disabled `prefs::kSigninAllowedOnNextStartup` by deault. The setting can be found at  `chrome://settings`:
"Allow Chromium sign-in - By turning this off, you can sign in to Google sites like Gmail without signing in to Chromium"

### CODE REVIEW

**Comment by Eloston** [comment]
> removed patches/iridium-browser/safe_browsing-support-trk-prefix.patch:

I don't think we need to preserve this patch; we don't support Safe Browsing.

> disabled prefs::kSigninAllowedOnNextStartup by deault. The setting can be found at chrome://settings:

Is this related to the Sync functionality (such as https://github.com/Eloston/ungoogled-chromium/issues/535#issuecomment-425679921 and #520)? I'm wondering how it's related. Also, does this flag still do anything even though the signin code is partially disabled?

**Comment by xsmile** [comment]
@Eloston It is definitely related but I didn't have the chance to investigate yet. I assume that it won't do anything since users cannot sign in into Chromium. In any case, disabling the preference should be the better option.

**Comment by Eloston** [comment]
I see, thanks. It definitely won't hurt to have it for now.

**Comment by Eloston** [comment]
I'm planning to merge after 70 becomes stable, unless you think there's a reason to merge earlier. I'll ask if you're ready to merge when the time comes.

**Comment by xsmile** [comment]
Alright, I will most likely refresh the patches and add the lists once the stable build is published.

**Comment by csagan5** [comment]
I had tried myself to port the safebrowsing-eviction patch to v70, didn't manage; glad you have a working version here.

I have some additional changes for Android (the v69 addendum is here: https://github.com/bromite/bromite/blob/master/patches/BRM080_Fixes-for-building-without-safebrowsing-on-Android.patch), I will publish the new version adapted for v70. Not sure you should include it now if you're not building for Android (might quickly go stale) but I thought to mention it here for other people trying to build for Android without safe browsing.

**Comment by xsmile** [comment]
I refreshed the existing and updated patches for Debian which include an important change:
The path to the master_preferences file was changed from `/usr/share/chromium/master_preferences` to `/etc/chromium/master_preferences`.

@csagan5 I did a few Android builds to test compatibility with the ungoogled patchset but I don't think I will continue to do it. It's probably better to keep the patches separated for now.
Nevertheless, it's nice to see the safebrowsing patches included in Bromite.

**Comment by Eloston** [comment]
@csagan5 I agree with @xsmile. It's better to exclude Android-specific patches until Android support gets added into ungoogled-chromium. I don't see any benefit of including those patches ahead of time.

@xsmile Thanks for updating the config. I've fixed the patch validator to attempt retries with a backoff.

**Comment by csagan5** [comment]
@Eloston we all agree 

> Not sure you should include it now if you're not building for Android (might quickly go stale)

**Comment by csagan5** [comment]
On a separate topic, is the canvas mitigation still effective? I got an issue report (https://github.com/bromite/bromite/issues/154) but not investigated yet.

**Comment by xsmile** [comment]
@csagan5 No issue here. The canvas fingerprint changes each time.

**Comment by csagan5** [comment]
The issue with canvas was due to an invalid automatic patch application with fuzziness, my bad; I have also updated the patch to use the optimisation of reduced rand() calls: https://github.com/bromite/bromite/blob/70.0.3538.71/patches/BRM053_Canvas-fingerprinting-mitigations-for-image-data-and-webGL.patch#L142

On another topic (sorry for going kinda-off-topic here): have you experienced issues at fetching the `webrtc` third-party dependency via git?
In v69 and v70 (and in the past as well) I cannot fetch the git commit specified in `DEPS` but rather I can get it via the web interface (https://chromium.googlesource.com/external/webrtc/).

@xsmile are you doing the same? Otherwise, how do you fetch webrtc via git? Just curious if for some reason I am not able to fetch it via git because the tree is not published via git but only via HTTP.

**Comment by xsmile** [comment]
@csagan5 This is the workaround I used for the WebRTC repository for 69: https://github.com/xsmile/ungoogled-chromium/blob/android/packaging/android/build.sh.ungoogin#L35.
I'm not sure why depot_tools doesn't find the commit and I assumed this is not an issue if you stick to the original build instructions.

**Comment by csagan5** [comment]
Thanks for the pointer! I use `gclient sync --upstream`, and in your script `--no-history --shallow` I guess have the same limitation/feature: they do not fetch extra refs, hence that's why it is needed to use the explicit fetch for the separate WebRTC tree.

**Pull request merged**
