### PR TITLE
Update to Chromium 91.0.4472.164

### PR DESCRIPTION
**Pull request by PF4Public**
While @Ahrotahn is preparing "The Next Big Thing", let's not bother him with such a trivial version bump. Shall we? ;)

### CODE REVIEW

**Comment by Ahrotahn** [comment]
Thanks!  This builds fine and I haven't ran into any issues running it so far!

**Comment by zhmars** [comment]
Thanks!

- [Blog entry](https://chromereleases.googleblog.com/2021/07/stable-channel-update-for-desktop.html)
- [Change log](https://chromium.googlesource.com/chromium/src/+log/91.0.4472.114..91.0.4472.164?pretty=fuller&n=10000)

**Comment by Area51Kacz** [comment]
Screenshot_2021-07-16_16-59-06

**Comment by Area51Kacz** [comment]
It works
Screenshot_2021-07-16_17-01-28

**Review by Eloston — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
