### PR TITLE
Update to Chromium 99.0.4844.51

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 99.0.4844.45 which should move to stable on the 1st.  

Notable changes:

* c++17 is being used in CFI builds now.  Be sure to update your toolchain and clear your ccache if you use that.  
* OS defines have been replaced with BUILDFLAGs:  [1234043](https://bugs.chromium.org/p/chromium/issues/detail?id=1234043)
* The trk patch has been updated to add a UTF-16 constant to follow [[3350885]](https://chromium-review.googlesource.com/c/chromium/src/+/3350885).  
* Remove-EV-certificates.patch has been simplefied due to [[3330334]](https://chromium-review.googlesource.com/c/chromium/src/+/3330334)
* The suggested changes in [#1817](https://github.com/Eloston/ungoogled-chromium/pull/1817#pullrequestreview-893258337) have been made.  

Linux builds with a newer glibc might require changes to sandbox/linux/services/credentials.cc.  The Gentoo repo has a patch for this already:  [chromium-glibc-2.34-r1.patch](https://github.com/gentoo/gentoo/blob/master/www-client/chromium/files/chromium-glibc-2.34-r1.patch).  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/98.0.4758.102..99.0.4844.45?pretty=fuller&n=10000)

EDIT: Updated to 99.0.4844.51 / @PF4Public

### CODE REVIEW

**Comment by Ahrotahn** [comment]
I'm going on a trip starting tomorrow morning and probably won't be able to make changes to this until I return on the 3rd.  
Please feel free to close this PR and use these changes as a base for further changes!

**Comment by PF4Public** [comment]
Did anyone have the time for a review? We could merge the PR to give proper credit on the changes.

**Comment by networkException** [comment]
There's the ability to edit the branch as a maintainer, right? And even if we would have to do completely seperate commits it's still possible to declare Ahrotahn as a co author

**Comment by PF4Public** [comment]
@networkException Have you tried building? They seem to have changed the logic in system-libraries somehow:
```sh
In file included from ../../media/mojo/services/gpu_mojo_media_client.cc:16:
In file included from ../../media/audio/audio_opus_encoder.h:16:
gen/shim_headers/opus_shim/third_party/opus/src/include/opus.h:5:10: error: 'opus.h' file not found with <angled> include; use "quotes" instead
#include <opus.h>
         ^~~~~~~~
         "opus.h"

```

**Comment by networkException** [comment]
I'm getting the same error

**Comment by PF4Public** [comment]
Mandriva has the solution: https://github.com/OpenMandrivaAssociation/chromium-browser-dev/blob/master/chromium-99-system-opus.patch

@perfect7gentleman found it.

**Comment by PF4Public** [comment]
Seems like "Sharing Hub" has no disable flag now:
image

**Comment by networkException** [comment]
thats annoying... As you already have a build, do you want to push updated patches (if any) and the updated pruning list to this branch?

**Comment by PF4Public** [comment]
Ready for review. Please do not squash while merging. Rebase instead.



> FILES.cfg seems to be removed in 99.x ([see here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/tools/build/README.md)), so [filescfg.py](https://github.com/Eloston/ungoogled-chromium/blob/master/utils/filescfg.py) no longer works.

@Niek Sorry for asking, but where is this script used?

**Review by networkException — APPROVED** [review]
Builds and runs fine

**Comment by kramred** [comment]
@PF4Public , you can (permanently) disable the sharing hub in the omnibox here (line 59):
[chrome/browser/sharing_hub/sharing_hub_features.cc](https://source.chromium.org/chromium/chromium/src/+/refs/tags/99.0.4844.51:chrome/browser/sharing_hub/sharing_hub_features.cc;l=59)

@Niek , if you're trying to build a portable version you can use the [FILES.cfg](https://github.com/kramred/ungoogled-chromium-portablelinux/blob/main/FILES.cfg) from my forked repo as an interim fix; that git commit also fixes the moved `ungoogled-chromium.desktop` link, see [diff](https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/compare/master...kramred:main?expand=1)

ungoogled-chromium 99.0.4844.51 also builds and runs on macOS (GitHub Actions for macOS is having some major issues with the upload and download of the artifacts again, hope it will be resolved soon and the builds will eventually finish)

**Comment by networkException** [comment]
Its getting kind of late with the update, how about we get it merged and do a follow up release in case of oversights?

**Review by PF4Public — APPROVED** [review]
As @networkException suggested.

**Comment by PF4Public** [comment]
@networkException will you add the tag?

**Pull request merged**
