### PR TITLE
add filter to compute_lists source_tree.rglob('*')

### PR DESCRIPTION
**Pull request by cjbd**
for #1389
this change updates `update_lists.py`, `compute_lists` function, to avoid scanning `.git` dirs, so that the script would work for local chromium repo cloned using `git` and `gclient` tools

tested on ubuntu 18 LTS, it's working

### CODE REVIEW

**Review by Eloston — CHANGES_REQUESTED** [review]
This is a good idea, but this implementation is too hacky.

I propose we add a new filtering scheme to `should_domain_substitute`, such as:

* `DOMAIN_EXCLUDE_PATTERNS` - Like the `INCLUDE` list of the same name, but does exclusions instead of inclusions
* `DOMAIN_EXCLUDE_PARTS` - Exclude paths containing at least one of the listed `Path.parts`

The new precedence order would be as follows:

- `DOMAIN_EXCLUDE_PREFIXES`
- *One of the new rules here*
- `DOMAIN_INCLUDE_PATTERNS`

@Ahrotahn What do you think?

**Comment by Ahrotahn** [comment]
I like that idea.  The current implementation is specific to the `.git` path, but having more granular exclude patterns would allow for other paths to excluded as needs arise.  For example it may be a good idea to include quilt's `.pc` path as a precaution as well.  

@cjbd's issue seemed to be with the binary check, so similar changes would also need to be in `should_prune`.

**Comment by cjbd** [comment]
@Eloston, i took another look, it seems the change to implement DOMAIN_EXCLUDE_PATTERNS and DOMAIN_EXCLUDE_PARTS is not a small one, i'm not sure my python skill is up to the task
and i don't fully understand what's the difference between DOMAIN_EXCLUDE_PATTERNS and existing DOMAIN_EXCLUDE_PREFIXES

@Ahrotahn, the filter i added can exclude pattern from both domain and prune lists

**Comment by cjbd** [comment]
@Eloston , i'm closing this PR, this project already covered source tar download, and there're many differences for repo cloned using git and gclient

**Comment by Eloston** [comment]
Sorry I couldn't get to implementing your change in a timely manner. If someone else wants to implement this, feel free.

**Pull request closed without merging**
