### PR TITLE
Upgrade to Chromium 81.0.4044.138

### PR DESCRIPTION
**Pull request by Zoraver**
No changes to the patches were needed. Chromium 81.0.4044.138 resolves 3 security issues.

I will let you know once I have a successful build.

### CODE REVIEW

**Comment by Zoraver** [comment]
My build succeeded; feel free to merge.

**Comment by PF4Public** [comment]
Gentoo ✔️

**Comment by jstkdng** [comment]
Same with Arch, though, there was a 0.04mb change in size, kinda weird for a security only release

**Comment by PF4Public** [comment]
They might have other changes, not only security fixes. Security fixes are the most important to mention, I suppose.

**Comment by lipici** [comment]
yey

**Comment by Ph0rk0z** [comment]
Are we sure vaapi still works? It was broken on all the builds in arch. Check media internals for mojovideodecoder

**Comment by jstkdng** [comment]
@Ph0rk0z 
my fork is on this release and vaapi works

**Comment by PF4Public** [comment]
@Ph0rk0z vaapi also works in Gentoo

**Comment by kevinlekiller** [comment]
@Ph0rk0z For Nvidia cards with driver (440.82) it's not working on Ungoogled Chromium, it does work on Chromium-vaapi

On Ungoogled Chromium 81.0.4044.138:

    00:00:00.347	kVideoDecoderName	"MojoVideoDecoder"
    00:00:00.347	kIsPlatformVideoDecoder	true
    00:00:00.348	info	"Selected MojoVideoDecoder for video decoding, config: codec: vp9, profile: vp9 profile0, level: not available, alpha_mode: is_opaque, coded size: [1280,720], visible rect: [0,0,1280,720], natural size: [1280,720], has extra data: false, encryption scheme: 
    Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
    00:00:00.348	pipeline_state	"kPlaying"
    00:00:00.349	error	"VDA Error 4"
    00:00:00.349	warning	"video fallback to new decoder after initial decode error."

On Chromium-vaapi 81.0.4044.138:

    00:00:00.336 | kVideoDecoderName | "MojoVideoDecoder"
    -- | -- | --
    00:00:00.336 | kIsPlatformVideoDecoder | true
    00:00:00.336 | info | "Selected MojoVideoDecoder for video decoding, config: codec: vp9, profile: vp 9 profile0, level: not available, alpha_mode: is_opaque, coded size: [3840,2160], visible rect: [0,0,3840,2160], natural size: [3840,2160], has extra data: false, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:LIMITED}"
    00:00:00.336 | pipeline_state | "kPlaying"
    00:00:00.338 | audio_buffering_state | {"state":"BUFFERING_HAVE_ENOUGH"}
    00:00:00.519 | dimensions | "3840x2160"
    00:00:00.519 | kResolution | "3840x2160"
    00:00:00.563 | video_buffering_state | {"state":"BUFFERING_HAVE_ENOUGH"}
    00:00:00.563 | pipeline_buffering_state | {"for_suspended_start":false,"state":"BUFFERING_HAVE_ENOUGH"}
    00:00:00.012 | duration | 365.621
    00:00:16.945 | info | "Selected video track: []"
    00:00:16.945 | video_buffering_state | {"state":"BUFFERING_HAVE_NOTHING"}
    00:00:16.946 | video_buffering_state | {"state":"BUFFERING_HAVE_ENOUGH"}

I tried looking at what patches Chromium-vaapi is using that Ungoogled Chromium isn't, but they both seem to be using the same patches, the only difference I see is Chromium-vaapi enables [this flag](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chromium-vaapi#n187) that I can't see in [Ungoogled Chromium](https://github.com/Eloston/ungoogled-chromium/blob/master/flags.gn) although I can't see why this flag would cause it to not work specifically on Nvidia.

**Pull request merged**
