### PR TITLE
Update to Chromium 91.0.4472.114

### LINKED ISSUE #1547: Updating to Chromium 91.0.4472.114
## Notes for the developer

Once you claim it, it is advisable that you create a [Draft Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) for increased visibility:

GitHub Interface for creating Draft Pull Requests

Finally, make sure to reference this issue in your PR.

Feel free to ask questions and discuss issues here along the way. Thanks!

## Notes for others

Feel free to raise issues or questions throughout the process. However, please refrain from asking ETAs unless no visible progress has been made here or on the developer's PR for a while (e.g. 2 weeks).

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates Chromium to 91.0.4472.114.  

---

The first commit updates to 91.0.4472.106.  This is one of the smaller updates I've seen.  No significant changes on ungoogled-chromium's side.  

[Blog entry](https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop_14.html)
[Change log](https://chromium.googlesource.com/chromium/src/+log/91.0.4472.101..91.0.4472.106?pretty=fuller&n=10000)

---

The second commit updates to 91.0.4472.114.  The only change needed for this one is a version bump.  

[Blog entry](https://chromereleases.googleblog.com/2021/06/stable-channel-update-for-desktop_17.html)
[Change log](https://chromium.googlesource.com/chromium/src/+log/91.0.4472.106..91.0.4472.114?pretty=fuller&n=10000)

---

Resolves #1547

### CODE REVIEW

**Comment by PF4Public** [comment]
[Looks good](https://github.com/PF4Public/ungoogled-chromium-bin/releases/tag/91.0.4472.106)

**Comment by Ahrotahn** [comment]
Another small update has released, so I've updated the PR to include it as well!

**Comment by bbwatch** [comment]
FWIW they seem to have `91.0.4472.115` now: https://chromium.googlesource.com/chromium/src/+/refs/tags/91.0.4472.115

**Comment by networkException** [comment]
New tags get pushed all the time but not every ends up as a stable release, see https://chromiumdash.appspot.com/releases?platform=Linux

**Review by Eloston — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
