### PR TITLE
Update to Chromium 96.0.4664.93

### LINKED ISSUE #1763: Updating to Chromium 96.0.4664.93
Could we update ungoogled to  96.0.4664.93

https://chromereleases.googleblog.com/2021/12/stable-channel-update-for-desktop.html

### PR DESCRIPTION
**Pull request by networkException**
This PR updates to chromium 96.0.4664.93

I've not seen notable changes to any patches, just different offsets

Builds and runs fine

Resolves #1763

### CODE REVIEW

**Comment by PF4Public** [comment]
Have you incorporated [suggestions from Zoraver from a previous PR](https://github.com/Eloston/ungoogled-chromium/pull/1732#pullrequestreview-811806284)? I'm just not sure to be seeing them. I may be wrong though.

**Comment by networkException** [comment]
I have not, I'm honestly not quite to which extent hunks should be moved to `remove-unused-preferences-fields.patch`

**Review by Ahrotahn — DISMISSED** [review]
Those sections can be moved in another patch, it's up to you if you want to handle that in this PR.  

It's a little weird that quilt is reordering those hunks, but otherwise this looks good to me and builds & runs fine on my end.

**Comment by networkException** [comment]
By section do you mean the include directive and piece of code below like

```diff
 #include "components/policy/core/common/policy_types.h"
-#include "components/safe_browsing/core/common/safe_browsing_prefs.h"
 #include "content/public/browser/browser_context.h"
 
 namespace base {
@@ -78,12 +77,6 @@ class ConnectorsService : public KeyedSe
   // is no token to use.
   absl::optional<std::string> GetDMTokenForRealTimeUrlCheck() const;
 
-  // Returns the value to used by the enterprise real-time URL check Connector
-  // if it is set and if the scope it's set at has a valid browser-profile
-  // affiliation.
-  safe_browsing::EnterpriseRealTimeUrlCheckMode GetAppliedRealTimeUrlCheck()
-      const;
-
   // Returns the CBCM domain or profile domain that enables connector policies.
```
?

Also this is my first time using quilt really, is there any faster way than pushing the patch I want to change and then manually call `quilt edit` on every file where I want to adjust something?

**Comment by Ahrotahn** [comment]
The include removals are all you would need to move.  
For quilt, source the `set_quilt_vars.sh` in the devutils directory.  Then you can refresh all of the patches in one go with `quilt push -a --refresh`.

**Review by PF4Public — APPROVED** [review]

**Comment by wchen342** [comment]
The patches mentioned in https://github.com/Eloston/ungoogled-chromium/pull/1750 is not included?

**Comment by PF4Public** [comment]
> The patches mentioned in #1750 is not included?

I thought @Ahrotahn will make another PR with them, wouldn't he?

**Review by Ahrotahn — APPROVED** [review]

**Comment by Ahrotahn** [comment]
Yeah, I figured we'd make another PR for that.  I'm strapped for time currently, so I might not be able to get that going until later.  I wanted to see what everyone's thoughts were on the best way to implement those changes and figured I'd make a discussion when I get the time.

**Pull request merged**
