### PR TITLE
Upgrade to Chromium 85.0.4183.121

### PR DESCRIPTION
**Pull request by Zoraver**
Addresses #1194. I will let you know once I have a successful build.

### CODE REVIEW

**Comment by kramred** [comment]
GitHub Actions build for macOS [85.0.4183.121-1.1](https://github.com/kramred/ungoogled-chromium-macos/releases/tag/85.0.4183.121-1.1)  (also) succeeded - no modification of patches was needed

**Comment by PF4Public** [comment]
@kramred Does Github allow long-running actions now? I remember this was impossible before.

**Comment by kramred** [comment]
No, it's still limited to 6 h per job. 
But you can create a chain of jobs, which is how the GitHub Actions build for macOS works (up to 3 jobs right now, i.e. up to 18 h) – the ninja build [receives](https://github.com/ungoogled-software/ungoogled-chromium-macos/blob/master/.github/scripts/github_build.sh#L19) a SIGTERM before the time runs out, the current state of the build is packed up, and uploaded for the following job.
@jstkdng mentioned the idea [here](https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/49)

**Comment by Zoraver** [comment]
My build succeeded and is running well; feel free to merge.

**Comment by Ahrotahn** [comment]
Builds and runs fine on my end, thanks Zoraver!

**Comment by PF4Public** [comment]
Confirm running fine on my system as well.

**Comment by jstkdng** [comment]
Had some issues on arch, but it is working now.

**Review by Eloston — APPROVED** [review]
LGTM, Thanks :+1:

**Pull request merged**
