### PR TITLE
Upgrade to Chromium 86.0.4240.75

### PR DESCRIPTION
**Pull request by Zoraver**
Addresses #1205. I will let you know once I have a successful build.

Notes:
* `extra/debian/warnings/initialization.patch` was removed as the third party code which it patched is no longer included in Chromium.
* `enable-default-reduced-referrer-granularity.patch` was removed as reduced referrer granularity is now enabled by default in Chromium.

### CODE REVIEW

**Comment by PF4Public** [comment]
It seems, that `components/safe_browsing/core/realtime/url_lookup_service_base.cc` also needs to be patched:


> ../../components/safe_browsing/core/realtime/url_lookup_service_base.cc:16:10: fatal error: 'components/safe_browsing/core/common/safe_browsing_prefs.h' file not found
> #include "components/safe_browsing/core/common/safe_browsing_prefs.h"
>          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
>

**Comment by perfect7gentleman** [comment]
```
../../content/browser/native_file_system/native_file_system_file_writer_impl.cc:502:41: error: no member named 'has_transient_user_activation_' in 'content::NativeFileSystemFileWriterImpl'
  item->has_user_gesture = file_writer->has_transient_user_activation_;
                           ~~~~~~~~~~~~~^
../../content/browser/native_file_system/native_file_system_file_writer_impl.cc:503:49: error: no member named 'PerformAfterWriteChecks' in 'content::NativeFileSystemPermissionContext'
  file_writer->manager()->permission_context()->PerformAfterWriteChecks(
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
2 errors generated.
ninja: subcommand failed
```

**Comment by PF4Public** [comment]
I allowed ninja to run for as long as possible. Apart from already reported, I've got following files:

> ../../components/safe_browsing/core/realtime/url_lookup_service_base.cc:452:7: error: use of undeclared identifier 'IsEnhancedProtectionEnabled'
>       IsEnhancedProtectionEnabled(*pref_service_)
>       ^
> ../../components/safe_browsing/core/realtime/url_lookup_service_base.cc:454:13: error: use of undeclared identifier 'IsExtendedReportingEnabled'
>           : IsExtendedReportingEnabled(*pref_service_)
>             ^
> 2 errors generated.
> ../../components/safe_browsing/core/realtime/policy_engine.cc:167:21: error: no member named 'kSafeBrowsingEnterpriseRealTimeUrlCheckMode' in namespace '
> prefs'
>              prefs::kSafeBrowsingEnterpriseRealTimeUrlCheckMode) ==
>              ~~~~~~~^
> ../../components/safe_browsing/core/realtime/policy_engine.cc:168:10: error: use of undeclared identifier 'REAL_TIME_CHECK_FOR_MAINFRAME_ENABLED'
>          REAL_TIME_CHECK_FOR_MAINFRAME_ENABLED;
>          ^
> 2 errors generated.
> ../../chrome/browser/policy/configuration_policy_handler_list_factory.cc:1438:11: error: no member named 'kSafeBrowsingWhitelistDomains' in namespace 'pr
> efs'; did you mean 'key::kSafeBrowsingWhitelistDomains'?
>           prefs::kSafeBrowsingWhitelistDomains, base::Value::Type::LIST),
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           key::kSafeBrowsingWhitelistDomains
> gen/components/policy/policy_constants.h:685:19: note: 'key::kSafeBrowsingWhitelistDomains' declared here
> extern const char kSafeBrowsingWhitelistDomains[];
>                   ^
> ../../chrome/browser/policy/configuration_policy_handler_list_factory.cc:1441:11: error: no member named 'kSafeBrowsingWhitelistDomains' in namespace 'pr
> efs'; did you mean 'key::kSafeBrowsingWhitelistDomains'?
>           prefs::kSafeBrowsingWhitelistDomains, base::Value::Type::LIST)));
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           key::kSafeBrowsingWhitelistDomains
> gen/components/policy/policy_constants.h:685:19: note: 'key::kSafeBrowsingWhitelistDomains' declared here
> extern const char kSafeBrowsingWhitelistDomains[];
>                   ^
> ../../chrome/browser/policy/configuration_policy_handler_list_factory.cc:1534:11: error: no member named 'kSafeBrowsingEnterpriseRealTimeUrlCheckMode' in
>  namespace 'prefs'; did you mean 'key::kEnterpriseRealTimeUrlCheckMode'?
>           prefs::kSafeBrowsingEnterpriseRealTimeUrlCheckMode, chrome_schema));
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           key::kEnterpriseRealTimeUrlCheckMode
> gen/components/policy/policy_constants.h:387:19: note: 'key::kEnterpriseRealTimeUrlCheckMode' declared here
> extern const char kEnterpriseRealTimeUrlCheckMode[];
>                   ^
> 3 errors generated.
>

**Comment by PF4Public** [comment]
with 3e42cc0 : 
> ../../chrome/browser/policy/configuration_policy_handler_list_factory.cc:1438:11: error: no member named 'kSafeBrowsingWhitelistDomains' in na
> mespace 'prefs'; did you mean 'key::kSafeBrowsingWhitelistDomains'?
>           prefs::kSafeBrowsingWhitelistDomains, base::Value::Type::LIST),
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           key::kSafeBrowsingWhitelistDomains
> gen/components/policy/policy_constants.h:685:19: note: 'key::kSafeBrowsingWhitelistDomains' declared here 
> extern const char kSafeBrowsingWhitelistDomains[];
>                   ^
> ../../chrome/browser/policy/configuration_policy_handler_list_factory.cc:1441:11: error: no member named 'kSafeBrowsingWhitelistDomains' in na
> mespace 'prefs'; did you mean 'key::kSafeBrowsingWhitelistDomains'?
>           prefs::kSafeBrowsingWhitelistDomains, base::Value::Type::LIST)));
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           key::kSafeBrowsingWhitelistDomains
> gen/components/policy/policy_constants.h:685:19: note: 'key::kSafeBrowsingWhitelistDomains' declared here 
> extern const char kSafeBrowsingWhitelistDomains[];
>                   ^
> ../../chrome/browser/policy/configuration_policy_handler_list_factory.cc:1534:11: error: no member named 'kSafeBrowsingEnterpriseRealTimeUrlCh
> eckMode' in namespace 'prefs'; did you mean 'key::kEnterpriseRealTimeUrlCheckMode'?
>           prefs::kSafeBrowsingEnterpriseRealTimeUrlCheckMode, chrome_schema));
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>           key::kEnterpriseRealTimeUrlCheckMode
> gen/components/policy/policy_constants.h:387:19: note: 'key::kEnterpriseRealTimeUrlCheckMode' declared here
> extern const char kEnterpriseRealTimeUrlCheckMode[];
>                   ^
> 3 errors generated.
>

**Comment by PF4Public** [comment]
Compiled at 2a793cf
Seems overall functional.

**Comment by Zoraver** [comment]
My build also succeeded and is running well. I am going to test it a bit more and then mark this as ready for review.

**Comment by Ahrotahn** [comment]
2a793cf gets me a functional build as well.  Thanks Zoraver!

**Comment by perfect7gentleman** [comment]
`Version 86.0.4240.75 (Official Build) (with ungoogled-chromium patches) (64-bit)`

**Comment by PF4Public** [comment]
@Zoraver You could probably bump this PR to 86.0.4240.80, as it is now available.

**Comment by Zoraver** [comment]
@PF4Public I have compiled ungoogled-chromium 86.0.4240.80 for the macOS target. I would be happy to bump this PR to 86.0.4240.80 if @Eloston would like me to; the reason I held off is that Chromium 86.0.4240.80 is only considered stable on macOS. I feel like the right approach would be to add a temporary mac-specific branch that bumps the version to 86.0.4240.80.

**Comment by PF4Public** [comment]
>86.0.4240.80 is only considered stable on macOS
Hmm, indeed, didn't read that news item thoroughly.

**Comment by Eloston** [comment]
Given [the diff between 75 and 80](https://chromium.googlesource.com/chromium/src/+/c69c33933bfc72a159aceb4aeca939eb0087416c..c786e242f9b11a070075c6c5ed0573ff18cd80ae) hardly changes anything outside of macOS and ChromeOS, I think it's safe to update to 80 for all platforms.

**Review by Eloston — APPROVED** [review]
LGTM, Thanks :+1:

**Pull request merged**
