### PR TITLE
Update to Chromium 94.0.4606.61

### LINKED ISSUE #1661: Updating to Chromium 94.0.4606.61
## Notes for the developer

Once you claim it, it is advisable that you create a [Draft Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) for increased visibility:

GitHub Interface for creating Draft Pull Requests

Finally, make sure to reference this issue in your PR.

Feel free to ask questions and discuss issues here along the way. Thanks!

## Notes for others

Feel free to raise issues or questions throughout the process. However, please refrain from asking ETAs unless no visible progress has been made here or on the developer's PR for a while (e.g. 2 weeks).

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates Chromium to 94.0.4606.61.  There are no notable changes on ungoogled-chromium's end.  

Fixes #1661

[Blog post](https://chromereleases.googleblog.com/2021/09/stable-channel-update-for-desktop_24.html)
[Change log](https://chromium.googlesource.com/chromium/src/+log/94.0.4606.54..94.0.4606.61?pretty=fuller&n=10000)

### CODE REVIEW

**Comment by PF4Public** [comment]
Looks like I was a little bit too fast, just a tiny bit too fast :D

**Comment by networkException** [comment]
Indeed :D Ah well, more releases don't hurt either.

Just finished building, runs fine for me

**Review by networkException — APPROVED** [review]

**Comment by PF4Public** [comment]
@networkException Did you use ccache right now or was it a clean rebuild?

**Comment by networkException** [comment]
I have ccache installed but I doubt it cached much. I have a Ryzen 9 5950X so builds are insanely fast :)

**Comment by PF4Public** [comment]
> I doubt it cached much

Exactly what I wanted to know! :) This bothers me actually. I see less and less cache hits even with minor updates :( First jumbo, then ccache, unfair! :(

**Comment by networkException** [comment]
My result isn't really representative, it probably caps at 1GB or something. I never bothered with adjusting cache size for chromium as it's fast enough anyways

**Comment by PF4Public** [comment]
Oh, I think I know what's the reason for ccache misses. I always build with PGO and LTO, bur they've changed the way PGO is shipped and are changing the filename of profile data each release, which spoils the flags and results in cache misses.

**Comment by Haus1** [comment]
Between DCHECK, all the account management workarounds and a million little things I've yet to get a good build. That should change here soon though with a patch to follow.

**Review by Zoraver — APPROVED** [review]
Looks good to me!

**Comment by PF4Public** [comment]
It is necessary to push a tag for GithubActions to create a new release. @Zoraver didn't you push a tag on purpose?

**Comment by networkException** [comment]
I've pushed it again.

**Comment by wchen342** [comment]
Actually I am getting
```
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc: In member function 'void PrimaryAccountManager::SetSyncPrimaryAccountInternal(const CoreAccountInfo&)':
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc:137:48: error: 'kGoogleServicesConsentedToSync' is not a member of 'prefs'
[ 5342s]   137 |         client_->GetPrefs()->GetBoolean(prefs::kGoogleServicesConsentedToSync);
[ 5342s]       |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc: In member function 'void PrimaryAccountManager::SetPrimaryAccountInternal(const CoreAccountInfo&, bool)':
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc:162:16: warning: unused variable 'prefs' [-Wunused-variable]
[ 5342s]   162 |   PrefService* prefs = client_->GetPrefs();
[ 5342s]       |                ^~~~~
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc:163:22: warning: unused variable 'account_id' [-Wunused-variable]
[ 5342s]   163 |   const std::string& account_id = primary_account_info_.account_id.ToString();
[ 5342s]       |                      ^~~~~~~~~~
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc: In member function 'void PrimaryAccountManager::OnSignoutDecisionReached(signin_metrics::ProfileSignout, signin_metrics::SignoutDelete, PrimaryAccountManager::RemoveAccountsOption, bool, SigninClient::SignoutDecision)':
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc:264:6: warning: suggest explicit braces to avoid ambiguous 'else' [-Wdangling-else]
[ 5342s]   264 |   if (assert_signout_allowed)
[ 5342s]       |      ^
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc: In member function 'bool PrimaryAccountManager::HasPrimaryAccount(signin::ConsentLevel) const':
[ 5342s] ../../components/signin/internal/identity_manager/primary_account_manager.cc:179:1: warning: control reaches end of non-void function [-Wreturn-type]
[ 5342s]   179 | }
[ 5342s]       | ^
```

on Fedora. It's easy to fix and I can create a patch myself, but I wonder why this doesn't happen on other Linux distros?

**Comment by Ahrotahn** [comment]
That seems to be the same thing encountered in #1666.  
Maybe there has been some other changes with how the flags operate in 94.

**Comment by wchen342** [comment]
Ah you are right. I forgot the differences in `is_official_build`. I will just create a platform-specific patch then.

**Comment by wchen342** [comment]
I figured it out.

The change comes from `build/config/dcheck_always_on.gni`, now it has
```
  # Set to false to disable DCHECK in Release builds. This is enabled by default
  # for non-official builds on the below platforms.
  dcheck_always_on =
      (build_with_chromium && !is_official_build) || dcheck_is_configurable
```

So I suggest adding the gn flag `dcheck_always_on=false` to the flag file.

**Pull request merged**
