### PR TITLE
Update to Chromium 96.0.4664.110

### LINKED ISSUE #1770: Updating to Chromium 96.0.4664.110
## Notes for the developer

Once you claim it, it is advisable that you create a [Draft Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests) for increased visibility:

GitHub Interface for creating Draft Pull Requests

Finally, make sure to reference this issue in your PR.

Feel free to ask questions and discuss issues here along the way. Thanks!

## Notes for others

Feel free to raise issues or questions throughout the process. However, please refrain from asking ETAs unless no visible progress has been made here or on the developer's PR for a while (e.g. 2 weeks).

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to Chromium 96.0.4664.110.  There were no notable changes on ungoogled-chromium's end.  

Fixes #1770 

[Blog post](https://chromereleases.googleblog.com/2021/12/stable-channel-update-for-desktop_13.html)
[Change log](https://chromium.googlesource.com/chromium/src/+log/96.0.4664.93..96.0.4664.110?pretty=fuller&n=10000)

### CODE REVIEW

**Review by networkException — APPROVED** [review]
Builds and runs fine

**Review by wchen342 — APPROVED** [review]
Builds fine for Android.

**Review by PF4Public — APPROVED** [review]
Builds and runs on Gentoo.

@networkException Would you mind merging and tagging?

**Comment by networkException** [comment]
Sure, I'll be at my pc in ~40m

**Pull request merged**
