### PR TITLE
Remove lines causing Android build to fail

### PR DESCRIPTION
**Pull request by wchen342**
The removed lines in the patch will lead to wrong number of arguments when building for Android.

### CODE REVIEW

**Comment by wchen342** [comment]
So the original source code looks like this:
```
      case BrowserSigninMode::kEnabled:
        prefs->SetValue(
#if defined(OS_ANDROID)
            // The new kSigninAllowedOnNextStartup pref is only used on Desktop.
            // Keep the old kSigninAllowed pref for Android until the policy is
            // fully deprecated in M71 and can be removed.
            prefs::kSigninAllowed,
#else
            prefs::kSigninAllowedOnNextStartup,
#endif
            base::Value(true));
        break;
      case BrowserSigninMode::kDisabled:
        prefs->SetValue(
#if defined(OS_ANDROID)
            // The new kSigninAllowedOnNextStartup pref is only used on Desktop.
            // Keep the old kSigninAllowed pref for Android until the policy is
            // fully deprecated in M71 and can be removed.
            prefs::kSigninAllowed,
#else
            prefs::kSigninAllowedOnNextStartup,
#endif
            base::Value(false));
        break;
```

The current patch actually does nothing for non-Android systems because if you look at the macro, the line current patch deleted is wrapped in `#if defined(OS_ANDROID)`. However, on Android because of the macro and the deleted line, now `prefs->SetValue()` will get one argument instead of two. Not sure about `signin_pref_names.h` but I have sucessfully built Android version with the original source of this part, so I think it should be fine.

**Comment by wchen342** [comment]
Ok so when I built my Android build, I actually put `prefs::kSigninAllowedOnNextStartup` there which is not supposed to exist in Android version. That's why the build was successful. So I think the two `case` sections should be removed altogether. Will test on Arch version and report back.

**Comment by Eloston** [comment]
> I actually put prefs::kSigninAllowedOnNextStartup there which is not supposed to exist in Android version. That's why the build was successful. So I think the two case sections should be removed altogether. 

I see, thanks for investigating. I must've forgotten about Android when writing this patch.

**Comment by wchen342** [comment]
I have updated the patch. I tested it on Arch and it works all right.

**Pull request merged**
