### PR TITLE
Fix macOS patches

### PR DESCRIPTION
**Pull request by tectiv3**
Removed fix-widevine patch
Fixed visibility.cc type error
```
 no viable conversion from returned value of type 'unique_ptr<base::ListValue, default_delete<base::ListValue>>' to function return type 'unique_ptr<base::Value, default_delete<base::Value>>'
```
Fixed memory_mapped_file error (probably this error exists only on 10.11)
```
memory_mapped_file_posix.cc:119:26: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to 'off_t' (aka 'long long') in initializer list
```

### CODE REVIEW

**Comment by tectiv3** [comment]
Don't merge it yet. I think my mapped_file fix isn't really a fix.
Chromium started to hang indefinitely (in uninterruptible state) so only system restart is able to kill it.

**Comment by tectiv3** [comment]
or may be it is a different problem, because according to:
https://chromium.googlesource.com/chromium/src/+/0413fd9f7c660ba7504dade7bb838862f138348e/base/files/memory_mapped_file_posix.cc#104
it is supposed to fallback to manual mode on everything that is not APFS.

So, this version is unstable for some other reason.

**Comment by tectiv3** [comment]
nope. Still crashing. So it's definitely something else.

**Comment by Eloston** [comment]
Alright. Let me know when it's ready to be reviewed.

**Comment by tectiv3** [comment]
It is ready.
The problem is not with my patches. But I need someone else to confirm it.

**Comment by kfur** [comment]
@tectiv3 I can. Just let me get your build image.

**Comment by Artur96** [comment]
@tectiv3 This PR builds and doesn't crash, but #315 still persists

**Comment by tectiv3** [comment]
@Artur96 it doesn't crash for me immediately. First time it did after a couple of hours of actively using it.

**Comment by Eloston** [comment]
The formatting looks fine, but I don't have the time to review the changes themselves to see how it works.

If you know how to reproduce the issue, you could try building with debug symbols and running a debugger. If you aren't able to diagnose the issue or resolve it, I can merge the changes and then create a new issue for this problem.

**Comment by tectiv3** [comment]
@Artur96 it's been two days, how does it work for you so far?

**Comment by Eloston** [comment]
@Artur96 Do you have a method to reproduce the crash or a stack trace? I would like to see if that crash will happen on my build.

The only patches I can tell that deal with TemplateURLRef directly are `inox-patchset/0008-restore-classic-ntp.patch` and `ungoogled-chromium/disable-google-host-detection.patch`. Though, nothing particularly stands out that could cause a crash in either of them.

**Comment by tectiv3** [comment]
@Artur96 does it actually crash? Because for me it's just freezing and ps reporting main chromium process is in `uninterruptible wait` (`UE` status).

**Comment by Artur96** [comment]
@tectiv3 It did actually crash, I have a [crash report](https://gist.github.com/Artur96/9295260ab20c9d373966cd99c56ad601).
@Eloston Unfortunately, not really. I was using the omnibox to perform a search.

**Comment by tectiv3** [comment]
for me it also freezing on search

**Comment by Eloston** [comment]
Could you guys try removing `ungoogled-chromium/add-flag-for-search-engine-collection.patch` and see if the crash still happens? If it does, try different combinations that include `ungoogled-chromium/disable-google-host-detection.patch` and `patches/inox-patchset/0008-restore-classic-ntp.patch` (these last two patches involve Template URLs in some form, but they don't modify them to the same level as the search collection patch).

Also, does the freezing happen consistently on every search, are there some fixed conditions that make it freeze/crash, or is it seemingly random?

**Comment by tectiv3** [comment]
I am not sure, cause first time I built and run it - it was couple of hours before it froze, but now I do remember it was on search.

I'll try it now.

**Comment by tectiv3** [comment]
Disabled `ungoogled-chromium/add-flag-for-search-engine-collection.patch`.
So far so good...

**Comment by Eloston** [comment]
Hmm, If @Artur96 can confirm, then I will investigate the patch.

**Comment by Artur96** [comment]
@Eloston So far the most probable way of inducing the crash is by typing `webrtc test` into the omnibar and clicking on the first result in DuckDuckGo. I'll try building without the mentioned patch and see if the crash still occurs.

**Comment by Eloston** [comment]
@Artur96 What is that first result that you find on DuckDuckGo? Perhaps that page is causing the issue.

**Comment by Artur96** [comment]
@Eloston https://test.webrtc.org/, it doesn't always cause a crash.

**Comment by tectiv3** [comment]
Still good on my side, doesn't crash on any DuckDuckGo query.
@Artur96 can you please upload your crashpad patch? I'm very eager to try it.

**Comment by Proteo** [comment]
Sorry to interrupt you guys, just wanted to let you know how much we, Mac users, appreciate your efforts. Ungoogled Chromium has been my main browser for a while now.
Thanks a a lot for your hard work!

**Comment by Artur96** [comment]
@tectiv3 I've submitted a PR to your fork

**Comment by tectiv3** [comment]
@Artur96 running it now, all good!

**Comment by tectiv3** [comment]
I've uploaded my build here: https://github.com/tectiv3/ungoogled-chromium-binaries/releases/tag/64.0.3282.186-1

**Comment by Eloston** [comment]
Alright, so here's what I'm going to do: I'll merge this PR first, and then @Artur96's fix for crashpad can be submitted as another PR. Then, I will create another issue to deal with the search collection bug.

**Comment by Artur96** [comment]
@tectiv3 removing `ungoogled-chromium/add-flag-for-search-engine-collection.patch` does fix the crash.

**Comment by Eloston** [comment]
@tectiv3 @Artur96 If you guys could check out #338, that would be great. I'm close to finishing the other changes for 64.0.3282.186-1, and would like to ensure that macOS support works.

**Comment by tectiv3** [comment]
okay, building it now

**Comment by tectiv3** [comment]
So far so good.

**Pull request merged**
