### PR TITLE
Official portable executable

### PR DESCRIPTION
**Pull request by mbakke**
Hi!

This adds a scheduled GitHub action that uploads an "official" portable Linux executable using GNU Guix.

It addresses #1532 and others.

Guix has a little-known feature to create relocatable binaries of any of its 17000+ packages with almost zero overhead.  This makes use of that feature such that the tarballs can be unpacked and run from anywhere.

It runs daily in order to get security updates, and aborts if the Guix CI system does not have an available "substitute" (build),  because Guix automatically falls back to building locally which will time out on the GitHub CI.

About the README diff: I actually did not change the third line, but Git is thorougly confused because the two sentences start similarly.

### CODE REVIEW

**Comment by mbakke** [comment]
I should mention that there will be situations where Guix lags behind official tags (rarely more than a couple of days), and also situations where Guix will be ahead of ungoogled-chromium (when @Eloston is busy and a new release is available).  So the uploaded release may not match the tag exactly.

**Comment by networkException** [comment]
First of all, packages for distributing ungoogled chromium have historically been a part of the [ungoogled-software](https://github.com/ungoogled-software) organisation. As your workflow is just a cron job I don't see why it has to be in the *main* repository, mainly containing patches and scripts to build ungoogled chromium.

Then what do you mean by "ahead of ungoogled-chromium"? If the patches in this repository don't get updated to a new version, its unlikely that it would compile. As such there is no "being ahead of ungoogled-chromium".

**Comment by mbakke** [comment]
With "ahead" I mean that if there is a new (minor) Chromium release, Guix will occasionally update to it before this repository has been updated, as long as the patches still apply.

Happy to move the scheduled job to a different repository, but I was not sure where.

**Comment by mbakke** [comment]
Oh, and if anyone wants to test the portable Guix build, it can be downloaded from here:

https://github.com/mbakke/ungoogled-chromium/releases/download/72.0.3626.122-1/ungoogled-chromium.tar.gz

Despite the 72 version in the URL, it is actually 91.0.4472.77.

**Comment by PF4Public** [comment]
If anyone asks me, I would reject this PR and redirect it into a separate platform repo.

**Comment by mbakke** [comment]
Instead of uploading a "random" version to the latest tag, one alternative could be to have a `latest` or `portable` tag which the scheduled job uploads to.

**Comment by mbakke** [comment]
I pushed a new commit that creates a `latest-portable` tag instead of hap-hazardly uploading the latest Guix version to the latest tag.

The version number in Guix actually includes the ungoogled-chromium commit ID it was built with, which is used to create the `latest-portable` tag.

Note: there is currently a bug that prevents the `latest-portable` tag from being updated.  I will fix that and squash these commits before removing the draft status if this approach looks sane.  Awaiting further feedback.

**Comment by Eloston** [comment]
I don't really understand the use-case of this change. Aside from the glaring problem that we don't put releases on this repo, why wouldn't users just install directly from Guix? Or why couldn't they use the AppImage or Flatpak builds?

**Comment by mbakke** [comment]
This is in response to #1532 and others where people have asked for a downloadable executable.

It is intended for users who can't or don't want to install Guix, Flatpak or whatever.  It has zero external dependencies and does not require root privileges to install or run. Perhaps it's better to target https://github.com/ungoogled-software/ungoogled-chromium-binaries instead?

**Comment by Eloston** [comment]
[AppImage](https://en.wikipedia.org/wiki/AppImage)'s primary objective is to have zero external dependencies and does not require root privileges to install or run. This is already available on the downloads page.

Also let's be clear here: From my perspective, #1532 is fundamentally an issue of trust. It is NOT a packaging issue. The issue of trust has been discussed before, it will never be solved (i.e. as good as inspecting the code and building the binary yourself), but it can be mitigated (e.g. reproducible binaries, CI/CD builds on trusted platforms with enough visibility, signing by trusted/regular members). I think the better course-of-action is to document a more in-depth explanation of this issue and the status quo.

By the way, if your change should target something, it should be Portable Linux. Let's not forget that ungoogled-chromium also runs on macOS, Windows, and Android, which are all quite different from Desktop Linux.

**Comment by PF4Public** [comment]
This PR does not fit this repository, so I'm closing it.

**Pull request closed without merging**
