### PR TITLE
Fix bug where chrome://settings/privacy cannot be loaded

### PR DESCRIPTION
**Pull request by Zoraver**
Addresses #930.

### CODE REVIEW

**Comment by jstkdng** [comment]
have you tested this? I'm gonna test it just in case.

**Comment by Zoraver** [comment]
I have tested it and it works on my machine™. Let me know how your test goes.

**Comment by jstkdng** [comment]
Nope, still doesn't show that setting, here is my build config.
https://build.opensuse.org/package/show/home:justkidding:arch/ungoogled-chromium

**Comment by jstkdng** [comment]
I'm building again just in case. Maybe I'm missing some flag?

**Comment by Zoraver** [comment]
If you go to chrome://settings in your most recent build and open the developer tools, do you see any errors logged to the console?

**Comment by jstkdng** [comment]
This is the log:
```
[Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.ch40mestatus.qjz9zk/features/5144752345317376 and https://developers.9oo91e.qjz9zk/web/updates/2019/07/web-components-time-to-upgrade for more details.
load_time_data.js:222 Unexpected condition on chrome://settings/: Could not find value for enableSafeBrowsingSubresourceFilter
expect @ load_time_data.js:222
getValue @ load_time_data.js:79
getBoolean @ load_time_data.js:184
value @ privacy_page.js:116
_initializeProperties @ polymer-extracted.js:11
_initializeProperties @ polymer-extracted.js:11
PropertiesChanged @ polymer-extracted.js:11
PropertyAccessors @ polymer-extracted.js:11
TemplateStamp @ polymer-extracted.js:11
PropertyEffects @ polymer-extracted.js:11
PropertiesMixin @ polymer-extracted.js:11
PolymerElement @ polymer-extracted.js:11
GestureEventListeners @ polymer-extracted.js:11
LegacyElement @ polymer-extracted.js:11
PolymerGenerated @ polymer-extracted.js:11
_stampTemplate @ polymer-extracted.js:11
_stampTemplate @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
MutableData @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
stamp @ polymer-extracted.js:11
(anonymous) @ settings_idle_load.js:59
(anonymous) @ polymer-extracted.js:11
whenImportsReady @ polymer-extracted.js:11
loadListener @ polymer-extracted.js:11
load (async)
Polymer.importHref @ polymer-extracted.js:11
importHref @ polymer-extracted.js:11
(anonymous) @ settings_idle_load.js:54
get @ settings_idle_load.js:53
requestIdleCallback (async)
attached @ settings_idle_load.js:35
attached @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
MutableData @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
_attachDom @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
_attachDom @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
window.Polymer._polymerFn @ polymer-extracted.js:11
window.Polymer @ polymer-extracted.js:11
(anonymous) @ settings_ui.js:20
Show 86 more frames
load_time_data.js:222 Unexpected condition on chrome://settings/: [undefined] (enableSafeBrowsingSubresourceFilter) is not a boolean
expect @ load_time_data.js:222
expectIsType @ load_time_data.js:234
getBoolean @ load_time_data.js:185
value @ privacy_page.js:116
_initializeProperties @ polymer-extracted.js:11
_initializeProperties @ polymer-extracted.js:11
PropertiesChanged @ polymer-extracted.js:11
PropertyAccessors @ polymer-extracted.js:11
TemplateStamp @ polymer-extracted.js:11
PropertyEffects @ polymer-extracted.js:11
PropertiesMixin @ polymer-extracted.js:11
PolymerElement @ polymer-extracted.js:11
GestureEventListeners @ polymer-extracted.js:11
LegacyElement @ polymer-extracted.js:11
PolymerGenerated @ polymer-extracted.js:11
_stampTemplate @ polymer-extracted.js:11
_stampTemplate @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
MutableData @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
stamp @ polymer-extracted.js:11
(anonymous) @ settings_idle_load.js:59
(anonymous) @ polymer-extracted.js:11
whenImportsReady @ polymer-extracted.js:11
loadListener @ polymer-extracted.js:11
load (async)
Polymer.importHref @ polymer-extracted.js:11
importHref @ polymer-extracted.js:11
(anonymous) @ settings_idle_load.js:54
get @ settings_idle_load.js:53
requestIdleCallback (async)
attached @ settings_idle_load.js:35
attached @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
MutableData @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
_attachDom @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
_attachDom @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
window.Polymer._polymerFn @ polymer-extracted.js:11
window.Polymer @ polymer-extracted.js:11
(anonymous) @ settings_ui.js:20
Show 86 more frames
polymer-extracted.js:11 Uncaught Error: Assertion failed: Pref is missing: safebrowsing.scout_reporting_enabled
    at assert (util.js:32)
    at HTMLElement.getPref (prefs_behavior.js:28)
    at HTMLElement.onSafeBrowsingReportingPrefChange_ (privacy_page.js:297)
    at Object.runMethodEffect [as fn] (polymer-extracted.js:11)
    at runEffectsForProperty (polymer-extracted.js:11)
    at runEffects (polymer-extracted.js:11)
    at HTMLElement._propertiesChanged (polymer-extracted.js:11)
    at HTMLElement._flushProperties (polymer-extracted.js:11)
    at HTMLElement._flushProperties (polymer-extracted.js:11)
    at HTMLElement.ready (polymer-extracted.js:11)
assert @ util.js:32
getPref @ prefs_behavior.js:28
onSafeBrowsingReportingPrefChange_ @ privacy_page.js:297
runMethodEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
MutableData @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
setTimeout (async)
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
stamp @ polymer-extracted.js:11
(anonymous) @ settings_idle_load.js:59
(anonymous) @ polymer-extracted.js:11
whenImportsReady @ polymer-extracted.js:11
loadListener @ polymer-extracted.js:11
load (async)
Polymer.importHref @ polymer-extracted.js:11
importHref @ polymer-extracted.js:11
(anonymous) @ settings_idle_load.js:54
get @ settings_idle_load.js:53
requestIdleCallback (async)
attached @ settings_idle_load.js:35
attached @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
__enableOrFlushClients @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
TemplateInstanceBase @ polymer-extracted.js:11
MutableData @ polymer-extracted.js:11
klass @ polymer-extracted.js:11
TemplateInstance @ polymer-extracted.js:11
__ensureInstance @ polymer-extracted.js:11
__render @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
(anonymous) @ polymer-extracted.js:11
microtaskFlush @ polymer-extracted.js:11
characterData (async)
run @ polymer-extracted.js:11
setConfig @ polymer-extracted.js:11
debounce @ polymer-extracted.js:11
__debounceRender @ polymer-extracted.js:11
runObserverEffect @ polymer-extracted.js:11
runEffectsForProperty @ polymer-extracted.js:11
runEffects @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
_attachDom @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
_attachDom @ polymer-extracted.js:11
_readyClients @ polymer-extracted.js:11
_flushClients @ polymer-extracted.js:11
_propertiesChanged @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
_flushProperties @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
ready @ polymer-extracted.js:11
_enableProperties @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
connectedCallback @ polymer-extracted.js:11
window.Polymer._polymerFn @ polymer-extracted.js:11
window.Polymer @ polymer-extracted.js:11
(anonymous) @ settings_ui.js:20
Show 86 more frames
settings_main.js:166 Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at HTMLElement.onShowingSection_ (settings_main.js:166)
    at HTMLElement.handler (polymer-extracted.js:11)
    at HTMLElement.fire (polymer-extracted.js:11)
    at main_page_behavior.js:242
onShowingSection_ @ settings_main.js:166
handler @ polymer-extracted.js:11
fire @ polymer-extracted.js:11
(anonymous) @ main_page_behavior.js:242
Promise.then (async)
scrollToSection_ @ main_page_behavior.js:240
currentRouteChanged @ main_page_behavior.js:301
currentRouteChanged @ basic_page.js:143
(anonymous) @ route.js:486
setCurrentRoute @ route.js:485
navigateTo @ route.js:556
onSelectorActivate_ @ settings_menu.js:99
handler @ polymer-extracted.js:11
fire @ polymer-extracted.js:11
_itemActivate @ iron-selectable-extracted.js:388
_activateHandler @ iron-selectable-extracted.js:380
handler @ polymer-extracted.js:11
_fire @ polymer-extracted.js:11
forward @ polymer-extracted.js:11
click @ polymer-extracted.js:11
_handleNative @ polymer-extracted.js:11
settings_main.js:166 Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at HTMLElement.onShowingSection_ (settings_main.js:166)
    at HTMLElement.handler (polymer-extracted.js:11)
    at HTMLElement.fire (polymer-extracted.js:11)
    at main_page_behavior.js:242
onShowingSection_ @ settings_main.js:166
handler @ polymer-extracted.js:11
fire @ polymer-extracted.js:11
(anonymous) @ main_page_behavior.js:242
Promise.then (async)
scrollToSection_ @ main_page_behavior.js:240
currentRouteChanged @ main_page_behavior.js:313
currentRouteChanged @ basic_page.js:143
(anonymous) @ route.js:486
setCurrentRoute @ route.js:485
navigateTo @ route.js:556
onSelectorActivate_ @ settings_menu.js:99
handler @ polymer-extracted.js:11
fire @ polymer-extracted.js:11
_itemActivate @ iron-selectable-extracted.js:388
_activateHandler @ iron-selectable-extracted.js:380
handler @ polymer-extracted.js:11
_fire @ polymer-extracted.js:11
forward @ polymer-extracted.js:11
click @ polymer-extracted.js:11
_handleNative @ polymer-extracted.js:11
```

**Comment by Zoraver** [comment]
Alright. That looks very similar to the errors that I observed before I changed `remove-unused-preferences-fields.patch`. I am going to do a clean rebuild to make sure that the problem isn't on my end.

**Comment by jstkdng** [comment]
Ok, just tested the new build, so far it is working. Thanks m8! Gonna wait for Eloston to merge this before uploading my build to my repository.

**Comment by Zoraver** [comment]
I'm glad to hear that. My clean rebuild is also running well.

**Comment by PF4Public** [comment]
Could this really be caught with automated testing? It is UI after all.

**Comment by Eloston** [comment]
@PF4Public I'm assuming that Chromium has a way to test the page's underlying control logic and data models (or in a MVC design pattern, the model and controller) without having to render the UI. Especially since Chromium is using Node.js in the build process, I'd assume they'd use it for testing.

**Pull request merged**
