### PR TITLE
Add two flags, one to disable GREASE for TLS, another to change the HTTP Accept header

### PR DESCRIPTION
**Pull request by carlob415**
related to issue #783.

### CODE REVIEW

**Comment by PF4Public** [comment]
Is it useful without patching `FrameAcceptHeaderValue`?

**Comment by carlob415** [comment]
I plan a separate flag for changing the Accept header.

**Comment by carlob415** [comment]
I have appended a second flag to change the default HTTP Accept header.

**Comment by PF4Public** [comment]
Are changes in this PR sufficient to close the related issue?

How should `kOsAll, ORIGIN_LIST_VALUE_TYPE("http-accept-header", "")},` function: It accepts a string, that is substituted into the header?

**Comment by PF4Public** [comment]
@networkException @Ahrotahn Do you have any opinion on the proposed changes?

**Review by networkException — DISMISSED** [review]
LGTM

**Comment by Ahrotahn** [comment]
This worked well for me.  It'll need to be updated over all the new changes to pass the tests though.  

<br>

> How should `kOsAll, ORIGIN_LIST_VALUE_TYPE("http-accept-header", "")},` function: It accepts a string, that is substituted into the header?

Yeah, that's one of the easier ways of having a custom text field in `chrome://flags`.

**Review by networkException — DISMISSED** [review]

**Comment by networkException** [comment]
The merge commit is a bit ugly but it shouldn't matter when squashed

**Comment by networkException** [comment]
also ci still fails

**Comment by PF4Public** [comment]
> also ci still fails

Sorry, I got ahead of myself and forgot to refresh patches. Already fixing it :)

**Review by networkException — APPROVED** [review]

**Comment by PF4Public** [comment]
Is wording OK? Merging?

**Comment by networkException** [comment]
yep I'd say so

**Pull request merged**
