### PR TITLE
devutils/validate_patches: Allow comments

### PR DESCRIPTION
**Pull request by xsmile**
Lines starting with '#' will be ignored.

### CODE REVIEW

**Comment by Eloston** [comment]
Hmm, I didn't realize that quilt allowed comments in series files. If we're going to allow comments, then we should update all the `utils` and `devutils` to be consistent. I'll need to look into this further.

**Comment by xsmile** [comment]
Usually I write comments directly in the series file. The final version of the file should probably not contain any, but it certainly helps while refreshing patches.
I would appreciate such an option, if it doesn't involve too many changes.

**Comment by Eloston** [comment]
So far I have left notes about patches in the patch files themselves. I'm not entirely sure what I would use comments for in the series file. How are you using this in your workflow?

**Comment by xsmile** [comment]
Mostly to toggle inclusion of patches and sometimes for notes while updating them. There are of course other ways to handle it.

**Pull request closed without merging**
