### PR TITLE
windows: Add packaging script

### PR DESCRIPTION
**Pull request by squalus**
This adds to the Windows build a Python script that creates a zip file of the build outputs

### CODE REVIEW

**Comment by squalus** [comment]
This adds to the Windows build a Python script that creates a zip file of the build outputs

**Comment by Eloston** [comment]
It seems we've run into a race condition; I did bedf856a4b9680756b562c963720de29b8b02157 before I noticed you submitted this PR. Sorry for not giving a notice ahead of time; I'll create more issues for tasks like these to better coordinate our efforts next time.

I haven't fully tested what I've committed yet. If you could test the Windows side of it, that'll be of great help.

**Comment by squalus** [comment]
No problem! I'm glad to see this done either way. I tested your change on Windows and got this error running package.bat:

```
Traceback (most recent call last):
  File "C:\Users\vagrant\Desktop\ungoogled-chromium\buildspace\tree\ungoogled_packaging\\scripts\process_build_outputs.py", line 155, in <module>
    main()
  File "C:\Users\vagrant\Desktop\ungoogled-chromium\buildspace\tree\ungoogled_packaging\\scripts\process_build_outputs.py", line 152, in main
    args.callback(args)
  File "C:\Users\vagrant\Desktop\ungoogled-chromium\buildspace\tree\ungoogled_packaging\\scripts\process_build_outputs.py", line 101, in _handle_archive
    for include_path in _include_paths(args, recursive=False):
  File "C:\Users\vagrant\Desktop\ungoogled-chromium\buildspace\tree\ungoogled_packaging\\scripts\process_build_outputs.py", line 70, in _include_paths
    for include_path in args.include_file:
AttributeError: 'Namespace' object has no attribute 'include_file'

```

**Comment by Eloston** [comment]
fd7bf846945e64f7c3fdfbfa4963af2e2589894c

**Comment by squalus** [comment]
Same error with fd7bf84. Changing `dest='append'` to `action='append'` in the `--include-dir` and `--include-file` arguments fixes it

**Comment by Eloston** [comment]
Oops. Yeah, it's supposed to be `action`.

**Comment by Eloston** [comment]
ee34616277d4f66fd3b9e3f97bb48ab7acc18698. If that works, I think we can close this PR.

**Comment by squalus** [comment]
That works! :+1:

**Pull request closed without merging**
