### PR TITLE
Sorted and more-or-less unified the list

### PR DESCRIPTION
**Pull request by PF4Public**

### CODE REVIEW

**Comment by PF4Public** [comment]
@briansoule, @braewoods, if you do not mind the rewording, please mark this PR as reviewed.

**Comment by braewoods** [comment]
@PF4Public Even if I wanted to I do not have such permissions to this repository.

**Comment by PF4Public** [comment]
I thought, @Eloston allowed anyone to review PR's:
image

Didn't he?

**Comment by braewoods** [comment]
I don't have that option here. AFAIK only approved folks can review changes.

**Comment by braewoods** [comment]
My mistake. I thought it was in this page.

**Comment by wchen342** [comment]
If you don't mind can you add [F-Droid](https://github.com/wchen342/ungoogled-chromium-android#f-droid-repository) for Android? I don't know whether it fits here though, since all other repositories are held by some organizations but this is my personal server.

**Comment by PF4Public** [comment]
> If you don't mind can you add [F-Droid](https://github.com/wchen342/ungoogled-chromium-android#f-droid-repository) for Android?

Sure, why not!

> all other repositories are held by some organizations

My overlay is far from being governed by Gentoo in any way ;) I believe, same applies to OBS for Debian and Ubuntu. 

So, in the end, most of the entries are custom works independent of "organizations".

**Comment by Eloston** [comment]
I will add F-Droid to the list after merging.

**Pull request merged**
