### PR TITLE
Replace PPA with OBS

### PR DESCRIPTION
**Pull request by braewoods**

### CODE REVIEW

**Comment by jstkdng** [comment]
Can't one use the OBS as a sort of ppa? I ask since an OBS project can be set up to be used as a repository under arch.

**Comment by braewoods** [comment]
Yes it can. The updated documentation replaces the PPA with a set of instructions for how to enable the OBS repository. I thought that much was obvious. Is there still some confusion about something?

**Comment by jstkdng** [comment]
calm down there m8, was just asking since I don't use the OBS for ubuntu stuff.
It's all good now.

**Comment by braewoods** [comment]
Ok. Sorry. I was just wondering if there was more to explain.

**Pull request merged**
