### PR TITLE
remove pdf plugin name patch

### PR DESCRIPTION
**Pull request by dot-gov**
Shouldn't be needed anymore because navigator.plugins returns a fixed list since Chrome 94. I tested tested using the [demo page](https://output.jsbin.com/nebaruc) and got the same output on Google Chrome an Chromium.

```
navigator.plugins:
    PDF Viewer
    Chrome PDF Viewer
    Chromium PDF Viewer
    Microsoft Edge PDF Viewer
    WebKit built-in PDF

navigator.mimetypes:
    application/pdf
    text/pdf
```

https://chromestatus.com/feature/5741884322349056

### CODE REVIEW

**Review by Ahrotahn — APPROVED** [review]
This looks good to me!

**Comment by PF4Public** [comment]
@Ahrotahn @networkException @Zoraver Is this a significant enough change for us to wait for @Eloston 's approval?

**Comment by networkException** [comment]
I think the normal two approvals are fine since its just cleanup

**Review by networkException — CHANGES_REQUESTED** [review]
Please also remove the entry from `flags.md` [line 35](https://github.com/dot-gov/ungoogled-chromium/blob/ef40202f723b5411cc08db1c6d3c2e191befc04e/docs/flags.md?plain=1#L35) and leftover bits to activate the flag in `add-components-ungoogled.cc` [line 39 to 41](https://github.com/dot-gov/ungoogled-chromium/blob/ef40202f723b5411cc08db1c6d3c2e191befc04e/patches/extra/ungoogled-chromium/add-components-ungoogled.patch#L39-L41) and [line 63](https://github.com/dot-gov/ungoogled-chromium/blob/ef40202f723b5411cc08db1c6d3c2e191befc04e/patches/extra/ungoogled-chromium/add-components-ungoogled.patch#L63)

**Review by networkException — APPROVED** [review]

**Review by Ahrotahn — APPROVED** [review]

**Pull request merged**
