### PR TITLE
Update to Chromium 99.0.4844.74

### PR DESCRIPTION
**Pull request by PF4Public**

### CODE REVIEW

**Review by networkException — APPROVED** [review]
Builds and runs fine, ty

**Comment by PF4Public** [comment]
I'm still building. Feel free to merge if all is OK.

**Comment by networkException** [comment]
Alright I'll merge this then :)

**Comment by networkException** [comment]
The tag is pushed already but GitHub Actions is experiencing issues right now, I will wait until its green on https://www.githubstatus.com/ and if the workflow didn't run then I'll just create a release manually

**Pull request merged**
