### PR TITLE
Update to 89.0.4389.90

### PR DESCRIPTION
**Pull request by Ahrotahn**
89.0.4389.90 released recently addressing some security issues.  There weren't any notable changes on our end. 

I'm currently most of the way through building and will update once it has completed.

### CODE REVIEW

**Comment by Ahrotahn** [comment]
My build completed successfully and I haven't encountered any issues testing it so far.  
The changes should be good to go!

**Review by Eloston — APPROVED** [review]
LGTM, Thanks :+1:

**Comment by Gribnif** [comment]
I'm not able to get this one to compile. About 25,000 files in I get this:
```
FAILED: obj/ui/gfx/memory_buffer_sources/io_surface.o
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/ui/gfx/memory_buffer_sources/io_surface.o.d -DGFX_IMPLEMENTATION -DOFFICIAL_BUILD -D_LIBCPP_HAS_NO_ALIGNED_ALLOCATION -DCR_XCODE_VERSION=1131 -DCR_CLANG_REVISION=\"llvmorg-12-init-16296-g5e476061-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DWEBP_EXTERN=extern -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_USE_LIBGIFCODEC -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DSK_BUILD_FOR_MAC -DSK_METAL -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../third_party/libwebp/src -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/skia -I../../third_party/libgifcodec -fno-delete-null-pointer-checks -fno-strict-aliasing -fstack-protector -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers -arch x86_64 -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wunguarded-availability -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-max-tokens -O2 -fno-omit-frame-pointer -g0 -isysroot ../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.11.0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -DPROTOBUF_ALLOW_DEPRECATED=1 -std=c++14 -fno-trigraphs -Wno-trigraphs -stdlib=libc++ -fno-exceptions -fno-rtti -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -c ../../ui/gfx/mac/io_surface.cc -o obj/ui/gfx/memory_buffer_sources/io_surface.o
../../ui/gfx/mac/io_surface.cc:167:28: error: use of undeclared identifier 'kCGColorSpaceITUR_2100_PQ'
        color_space_name = kCGColorSpaceITUR_2100_PQ;
                           ^
../../ui/gfx/mac/io_surface.cc:176:28: error: use of undeclared identifier 'kCGColorSpaceITUR_2100_HLG'; did you mean 'kCGColorSpaceITUR_2020_HLG'?
        color_space_name = kCGColorSpaceITUR_2100_HLG;
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           kCGColorSpaceITUR_2020_HLG
../../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGColorSpace.h:140:29: note: 'kCGColorSpaceITUR_2020_HLG' declared here
CG_EXTERN const CFStringRef kCGColorSpaceITUR_2020_HLG
                            ^
2 errors generated.
[25110/45941] OBJCXX obj/ui/gfx/animation/animation/animation_mac.o
ninja: build stopped: subcommand failed.
```
I'm building in MacOS 10.14.6.

**Comment by Ahrotahn** [comment]
I don't have a Mac so hopefully this helps, but from what I've found it looks like you'll need to update the MacOS SDK as it seems those [definitions only exist in version 11+](https://github.com/phracker/MacOSX-SDKs/search?q=kCGColorSpaceITUR_2100_HLG).  
The comments in `io_surface.cc` around line 153 mention this.  I'm surprised that they didn't use defines instead to avoid this issue.

**Comment by Gribnif** [comment]
Thanks for the reply, @Ahrotahn. You are probably right about the SDK being outdated. Unfortunately Apple, in their infinite wisdom, won't let me install a newer version of XCode with my (intentionally) old OS. There probably is some arcane way to get the latest SDK working with an older XCode, but I don't have the time to devote to such a project. For now I'm just using the homebrew binary you provided.

**Pull request merged**
