### PR TITLE
windows: Fix build

### PR DESCRIPTION
**Pull request by squalus**
* disable multi-dll build to avoid linker errors with iridum trk
  patches and profile-related code
* add new patch to fix non-multi-dll linker errors
* in windows safebrowsing patch, hack out a few lines of code causing
  crash on startup when creating a new profile

### CODE REVIEW

**Comment by squalus** [comment]
I used this config to get a successful build that withstood a few minutes of testing. I used LLVM 6.0.0

**Comment by Eloston** [comment]
Awesome!

Would you be able to post a binary to #345 for others to test? Thanks.

**Comment by squalus** [comment]
I'd rather not post binaries as the security of my Windows system is in doubt. If I can put together a better Windows environment then I may be able to do this in the future though

**Comment by Eloston** [comment]
I see. I'm sure we'll figure out some way to get a clean build soon enough.

**Comment by squalus** [comment]
Here are the outstanding issues I encountered. Thanks for the Windows building notes, those were helpful and some of these are noted there.

- build.bat script did not copy the args.gn file. Don't know why yet. Windows batch files are awful!
- quilt needed the series file to be in unix rather than windows (CRLF) format. Though this may have been because I was using WSL instead of MSYS2. I'll need to check this
- build.bat needs to have gperf/bison env vars set
- I needed to run the "x64 Native Tools" command prompt rather than use the entries in build.bat. Not sure why
- LLVM needs to be copied into tree (I have a patch coming to do this in getsrc)
- No packaging or installer at the end. I tried using `ninja mini-installer` but the installer did not start up. Haven't looked into it yet.

**Comment by squalus** [comment]
Also, I used the 64 bit LLVM 6.0.0 official binaries from llvm.org

**Pull request merged**
