### PR TITLE
Upgrade to Chromium 85.0.4183.102

### PR DESCRIPTION
**Pull request by Zoraver**
Addresses #1179. I will let you know once I have a successful build.

### CODE REVIEW

**Comment by Zoraver** [comment]
My build succeeded; feel free to merge.

**Comment by Ahrotahn** [comment]
Builds and runs fine on my end!

**Comment by PF4Public** [comment]
Tried changing network connectivity, no issues ;)

**Review by Eloston — APPROVED** [review]
LGTM, Thanks :+1:

**Pull request merged**
