### PR TITLE
Automatically creating an "Updating to Chromium x.x.x.x" issue

### PR DESCRIPTION
**Pull request by PF4Public**
I'll leave it running in my fork for a while. Apart from that, I'd like to get some feedback on this before squashing and marking as ready for review.

TODO list before squashing:
- [x] Change variable in `if: github.repository == `

### CODE REVIEW

**Comment by networkException** [comment]
Maybe there's an action that creates an issue if it doesn't exist? Instead of having two seperate steps for that, otherwise lgtm

**Comment by PF4Public** [comment]
> Maybe there's an action that creates an issue if it doesn't exist?

At the time of #1219 `JasonEtco/create-an-issue` didn't have such functionality, but it looks like it has `update_existing: true`  and `search_existing: all` nowadays, which might be good for us. I'll look into it.

**Comment by PF4Public** [comment]
dblock just published fixed version of `JasonEtco/create-an-issue`, so we are all set now and there's no need for forking. I'll leave it running in my fork for a while.

**Comment by networkException** [comment]
Not entirely sure but wouldn't it be cleaner to just have a seperate tag for update prs / issues?

**Comment by PF4Public** [comment]
I cannot think of anything better than just 'update' for a tag name. @networkException What would _you_ call it?

**Comment by networkException** [comment]
I mean thats descriptive so why not

**Comment by PF4Public** [comment]
It is indeed cleaner. And if no one claims it, we can put `help wanted` manually.
image

**Comment by networkException** [comment]
This might be a bit bikeshed-y but reading "Once you claim it, it is advisable that you create a Draft Pull Request for increased visibility" does not really fit with how we are handling update prs currently.
Sure drafts very much have their place for larger updates that require thorough review or for updating to non stable (but soon to be stable) branches, but there is no need to increase visibility if there are only a hand full prs open.

How about we replace that portion with a link to https://github.com/Eloston/ungoogled-chromium/blob/master/docs/developing.md#updating-patches perhaps?

**Comment by PF4Public** [comment]
Yes! @networkException you read my mind! I just wanted to rewrite the template a little bit, but ~didn't have the time for this~ was very lazy recently and was postponing this ever since :(

**Comment by networkException** [comment]
Oh yea thats very relatable, winter holidays kinda killed my productivity

**Comment by PF4Public** [comment]
At last I did some writing. Please see [the old template](https://github.com/PF4Public/ungoogled-chromium/issues/14) and [the new one](https://github.com/PF4Public/ungoogled-chromium/issues/16). 

Is the new one better or worse? I'm especially worried about the wording in it as it will be read many-many times. It should be flawless.

**Comment by networkException** [comment]
> This might be a bit bikeshed-y but reading "Once you claim it, it is advisable that you create a Draft Pull Request for increased visibility" does not really fit with how we are handling update prs currently. Sure drafts very much have their place for larger updates that require thorough review or for updating to non stable (but soon to be stable) branches, but there is no need to increase visibility if there are only a hand full prs open.

I think that point still holds, otherwise the new one looks good to me

**Comment by PF4Public** [comment]
> I think that point still holds

Oh, sorry @networkException, I forgot to reply to this point of yours. I think, that by "increased visibility" Eloston meant "claim this work" or "let others see and comment from the start". At least that's how I read this and in this context it looks fine to me. In the context of "make it obvious that you are about to submit a PR"… kind of… If you think it is dubious, we can and should rephrase that! In the end we can ping Eloston himself for his input on this one :)

**Comment by Eloston** [comment]
Overall I think the idea is good and the implementation LGTM.

> I think, that by "increased visibility" Eloston meant "claim this work" or "let others see and comment from the start"

It's been too long, so I don't know why I wrote this... if I had to guess, it's probably both of these reasons. From my current perspective, I think it is better to reword this because it isn't really necessary to use a draft PR to "claim this work". I find Draft PRs are best for those who prefer to work on large changes in steps and publish the progress online for others to track. The most useful scenario is if the PR author needs some high-level feedback before finalizing some changes. However, there are developers that prefer working offline until the change is completely done, so a Draft PR doesn't fit their workflow very well.

Perhaps we can rewrite this statement so we let developers choose a workflow. For example:

> If you'd like to increase visibility of your progress or get early feedback/advice, consider creating a Draft PR.

**Comment by PF4Public** [comment]
Marking as ready for review

**Review by networkException — APPROVED** [review]

**Review by Eloston — APPROVED** [review]

**Pull request merged**
