### PR TITLE
Update to Chromium 101.0.4951.64

### PR DESCRIPTION
**Pull request by jstkdng**
Well this update was simple, only CVEs and changes for M1 Macs and chrome os.

### CODE REVIEW

**Comment by PF4Public** [comment]
The more of us can bump releases the better!

**Comment by jstkdng** [comment]
@PF4Public how do you link issues to PRs?

**Comment by PF4Public** [comment]
And now we wait :)
```
2022-04-24T18:02:17 >>> www-client/ungoogled-chromium-101.0.4951.41_p1: 7 hours, 43 minutes, 33 seconds
2022-05-03T14:25:16 >>> www-client/ungoogled-chromium-101.0.4951.54_p1: 7 hours, 39 minutes, 48 seconds
```

**Review by Ahrotahn — APPROVED** [review]
Builds and runs fine on my end!

**Comment by jstkdng** [comment]
@Ahrotahn jesus that's fast af compilation.

It works in my end as well

image

**Comment by networkException** [comment]
Runs fine :+1:

**Comment by PF4Public** [comment]
> The Stable channel has been updated to 101.0.4951.67 for Windows which will roll out over the coming days/weeks.

 We could bump further to 67 if there is any reason to do so…

@jstkdng There is yet another way of linking issue: Writing "Fixes #1950" in original message (not necessary commit message, but that would also work) could do it. It just occured to me :)

**Pull request merged**
