### PR TITLE
Add flag to set whether a window should close with the last tab

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR adds a flag that allows the user to set whether a window should close when the last tab is closed.  
Closing the last tab will instead open a new tab when `close-window-with-last-tab` is set to `never`.  The window can still be closed via the menu, the titlebar, keyboard shortcut, etc.  

I was previously using an addon to handle this.  Unfortunately it needed to keep a blank tab pinned to function, polluted the tab history, and it also prevented dragging tabs between windows.  
It made more sense to add a few lines of code to implement the functionality.

### CODE REVIEW

**Review by Eloston — CHANGES_REQUESTED** [review]
Huh, interesting use-case. Code LGTM!

Could you also document this in `docs/flags.md`? Thanks!

**Comment by Ahrotahn** [comment]
Sure thing!  I've updated the commit.

**Review by Eloston — APPROVED** [review]
LGTM, Thanks :+1:

**Comment by snacktary** [comment]
Is it possible to close the whole chromium application after closing the last tab?

**Pull request merged**
