### PR TITLE
Update to Chromium 102.0.5005.61

### LINKED ISSUE #1935: fix-building-without-safebrowsing.patch incomplete?
Hi all,

while updating the windows build I encountered a linking error because the symbol `safe_browsing::EventResultToString` is not found. The function is used multiple times in the file `chrome/browser/extensions/api/safe_browsing_private/safe_browsing_private_event_router.cc`, but most calles are within `FULL_SAFE_BROWSING` ifdef blocks inserted by the `fix-building-without-safebrowsing.patch` patch except for one call around line 313 in function `SafeBrowsingPrivateEventRouter::OnPolicySpecifiedPasswordReuseDetected`.

The missing function is implemented in the file `chrome/browser/safe_browsing/cloud_content_scanning/deep_scanning_utils.cc` which is not compiled because the patch `0001-fix-building-without-safebrowsing.patch` disables compiling of the safe_browsing files defined in `chrome/browser/safe_browsing/BUILD.gn`.

I was wondering if windows is the only platform affected by this problem or if this should be fixed in this repo's patch.

### PR DESCRIPTION
**Pull request by Ahrotahn**
This PR updates to chromium 102.0.5005.61.  

Notes:

* The removal in `download_bubble_prefs.cc` in the safebrowsing patch is no longer needed [[3579726]](https://chromium-review.googlesource.com/c/chromium/src/+/3579726)

* There were changes needed to the safebrowsing patch in `safe_browsing_private_event_router.cc`.  Instead of updating that I've removed the previous changes and added changes that removes the file from being built along with the few places that call into it.  This should also resolve #1935 

* `ENABLE_PRINT_CONTENT_ANALYSIS` was added in [[3337977]](https://chromium-review.googlesource.com/c/chromium/src/+/3337977) which hooks into safebrowsing in other areas.  I've added changes to disable that in the safebrowsing patch.  

* There was a lot of activity in `configuration_policy_handler_list_factory.cc` in remove-unused-preferences-fields.patch, mostly due to the reorganization in [[3573473]](https://chromium-review.googlesource.com/c/chromium/src/+/3573473) and [[3576875]](https://chromium-review.googlesource.com/c/chromium/src/+/3576875).  The same keys are being removed as before.  

* `primary_account_policy_manager.cc` has been moved from components in [[3563021]](https://chromium-review.googlesource.com/c/chromium/src/+/3563021) which has changes in remove-unused-preferences-fields.patch and makes 0017-disable-new-avatar-menu.patch no longer needed 

* `AppsShortcutDefaultOff` has been removed from 0006-modify-default-prefs.patch due to [[3569271]](https://chromium-review.googlesource.com/c/chromium/src/+/3569271)

* Some removals and an addition to the trk patch: [[3572211]](https://chromium-review.googlesource.com/c/chromium/src/+/3572211), [[3537450]](https://chromium-review.googlesource.com/c/chromium/src/+/3537450)

* SwiftShader has been removed: [(1060139)](https://bugs.chromium.org/p/chromium/issues/detail?id=1060139)

* If you aren't yet using clang 15 you'll need to remove `-no-opaque-pointers` in `build/config/compiler/BUILD.gn`.  This is already removed in stha09's compiler patch.  

* The feature flag to hide the sidepanel button has been removed.  I'll submit a PR later on to add flags to hide the sidepanel and the share hub buttons.  

<br>

[Change log](https://chromium.googlesource.com/chromium/src/+log/101.0.4951.64..102.0.5005.61?pretty=fuller&n=10000)
[Blog post](https://chromereleases.googleblog.com/2022/05/stable-channel-update-for-desktop_24.html)

### CODE REVIEW

**Comment by PF4Public** [comment]
It seems that they are deprecating 32-bit support or what?

> ERROR at //BUILD.gn:1521:1: Assertion failed.
> assert(
> ^-----
> 'target_cpu=x86' is not supported for 'target_os=linux'. Consider omitting 'target_cpu' (default) or using 'target_cpu=
> x64' instead.
> See //BUILD.gn:1522:5:
>     is_valid_x86_target || target_cpu != "x86",
>     ^-----------------------------------------
> This is where it was set.
> 

Very funny:

> Reland "Reland "Prevent accidentally targeting x86""
> 
> This is a reland of commit 78e35bd82555c24dcdde644a6c9fbb4a2d353599
> After https://chromium-review.googlesource.com/c/chromium/src/+/3582603,
> linux-gcc-rel should be fine with the reland.
> 
> Original change's description:
> > Reland "Prevent accidentally targeting x86"
> >
> > This is a reland of commit 90af87c0d85c6c1060bd78465eea1a08690ed8cc
> > Now allows `use_libfuzzer || !build_with_chromium` on linux,
> > and the 32-bit linux main waterfall bot is gone now (see bug).
> >
> > Original change's description:
> > > Prevent accidentally targeting x86
> > >
> > > I spent a good hour or so today trying to figure out why my build was
> > > broken, turns out I just mistyped my target_cpu (should have just gone
> > > with the default). A bit of searching shows I'm not the first person to
> > > make this mistake, so now hopefully I'll be the last.

**Comment by Ahrotahn** [comment]
I hadn't seen any announcements on this yet.  According to [(1305287)](https://bugs.chromium.org/p/chromium/issues/detail?id=1305287) it seems there was an issue with some wayland change causing 32bit builds using libfuzzer to fail which explains why it's checked for explicitly in [[3583780]](https://chromium-review.googlesource.com/c/chromium/src/+/3583780).  It seems like a pretty janky way of dealing with that though.  Hopefully they can implement a proper fix before Tuesday.

**Comment by PF4Public** [comment]
They've rolled ffmpeg, so expect issues if building against ffmpeg-4. PF4Public/gentoo-overlay/issues/153

Apart from that, builds and runs fine on 64-bit. 👍🏻 Minimal referrer is still functioning ;)

**Comment by a61kt** [comment]
Im tryin it
https://build.opensuse.org/package/live_build_log/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium/Arch/x86_64

**Comment by a61kt** [comment]
@Ahrotahn Im tryin it ... thanks

https://build.opensuse.org/package/live_build_log/home:Area51Kacz:branches:home:ungoogled_chromium:testing/ungoogled-chromium/Arch/x86_64

**Comment by a61kt** [comment]
@PF4Public @Ahrotahn and could it work with CHROME ffmpe

with arch ffmpeg it fails too 
[_log.txt](https://github.com/Eloston/ungoogled-chromium/files/8758685/_log.txt)
g

**Comment by networkException** [comment]
Stop constantly mentioning the maintainers

**Comment by PF4Public** [comment]
Arch seems to be merely rolling ffmpeg back: https://github.com/archlinux/svntogit-packages/blob/140fa66be0604daaf16be4246053c1a359d4e3bb/trunk/PKGBUILD#L109-L111

I'll try the same :)

**Review by networkException — APPROVED** [review]
Builds and runs fine

**Comment by PF4Public** [comment]
@teeminus Have you had a chance to test this PR?

**Comment by PF4Public** [comment]
So… maybe ship it while teeminus is "fighting" Windows?

**Comment by networkException** [comment]
Sure :+1:

**Comment by Nifury** [comment]
@teeminus No idea why that error popped up...it compiles and runs fine on my end.

**Comment by teeminus** [comment]
> @teeminus No idea why that error popped up...it compiles and runs fine on my end. 

Yeah, my bad... I had to add a new patch to remove a clang-15 parameter (windows only has clang-14) and that patch was incomplete. Currently it's compiling and if that succeeds I will update the windows PR.

**Comment by PF4Public** [comment]
I wonder, why Nifury didn't get this error? Do you use different building scripts?

**Comment by teeminus** [comment]
Compiling and linking finished over night. I need to update the patches before pushing my changes and updating the PR.

**Comment by PF4Public** [comment]
Fun fact: Fingerprinting deception is a double-edged sword. Whatsapp web recently started checking browser fingerprint and nullifying the session if browser fingerprint changed. This results in session breaking upon browser restart :)

**Comment by PF4Public** [comment]
> you might as well use google chrome

Just for that? Nah, too much trouble.

**Pull request merged**
