### PR TITLE
proper detection and usage of c++-4.9 on MacOS fixing #78

### PR DESCRIPTION
**Pull request by takinbo**

### CODE REVIEW

**Comment by Eloston** [comment]
Hi, sorry it took me a little while to respond to your pull request as opposed to other issues here. I have a busy schedule with some variations, so I can only respond to issues on and off.

Anyway, does `c++-4.9` exist after `brew link gcc` is invoked, and does it always refer to the GCC C++ compiler? I was thinking that `g++-4.9` would be better to use since it generally implies GCC's version.

**Comment by Eloston** [comment]
@dangom @9Morello Sorry to bug you two, but do you know the answer to the question above? Here it is again for convenience:
> Anyway, does `c++-4.9` exist after `brew link gcc` is invoked, and does it always refer to the GCC C++ compiler? I was thinking that `g++-4.9` would be better to use since it generally implies GCC's version.

**Comment by 9Morello** [comment]
`c++-4.9` points by default to `/usr/local/bin/c++-4.9`.

**Comment by Eloston** [comment]
So what is `/usr/local/bin/c++-4.9` then? The GCC compiler? I'm worried that `c++` is ambiguous and may instead refer to clang if the versions happen to align. Does `g++-4.9` exist?

**Comment by 9Morello** [comment]
Sorry for not responding clearly before. Yes, it points to the GCC C++ compiler. (`/usr/local/Cellar/gcc49/4.9.3/bin/c++-4.9`). `g++-4.9` exists and its a shortcut to `/usr/local/Cellar/gcc49/4.9.3/bin/g++-4.9`.

**Comment by Eloston** [comment]
Cool, that's what I needed to know. Thanks

**Pull request closed without merging**
