### PR TITLE
Update stale issues and PRs workflow

### PR DESCRIPTION
**Pull request by PF4Public**
* Changed the default 60/7 days of inactivity to 14/14.
* Plus messages to convey the stale'ing and closing of the issues.

I'd like to hear from you all regarding the following:
1. I believe that default 60 days is way too much, but not certain if 14 is a reasonable value either. What you think?
2. How do you like the wording of the messages? Are they concise and make the point clear?

### CODE REVIEW

**Comment by Ahrotahn** [comment]
14/14 seems reasonable.  I guess that could always be adjusted in the future if there's issues with that timeframe.  

The close message might be more clear if rearranged slightly:  "This issue has been automatically closed as sufficient information hasn't been provided on the issue for further actions to be taken."

**Comment by tomasz1986** [comment]
I would just like to add that 2 weeks is nothing when people are busy with their lives (e.g. work, family, etc.). I've experienced this myself in different projects, when sometimes it may take months for someone to come back with the requested information.

Also, it's super annoying having to bump up the issue every few weeks just because it's been marked as "stale" by some bot, even though the issue itself hasn't been solved, and no developer has even had time to start working on it yet.

**Comment by PF4Public** [comment]
> I would just like to add that 2 weeks is nothing

After stale'ing there are another 2 weeks before closing. This is actually why I want to gather more feedback on the timings proposed. We may make it 30/7 for example.

> Also, it's super annoying having to bump up the issue every few weeks just because it's been marked as "stale" by some bot, even though the issue itself hasn't been solved, and no developer has even had time to start working on it yet.

The intention here is to stale _only those_ issues, which are marked with `need info` label, which should signify, that not enough information is available to proceed. If enough information is gathered, the label should be removed and a new one attached, like `enhancement` or `bug` etc. You may see, that this bot acts _only_ on `need info` issues and _ignores_ the rest.

> The close message might be more clear if rearranged slightly: "This issue has been automatically closed as sufficient information hasn't been provided on the issue for further actions to be taken."

Looks even better!

**Comment by wchen342** [comment]
I think 30/7 is a reasonable value. 14 is too short IMO.

**Comment by PF4Public** [comment]
I've squashed everything and put 30/7.

**Review by wchen342 — APPROVED** [review]
Maybe change `Feel free to add more information.` to `Feel free to add more information so that we can re-open the issue.`. Otherwise LGTM.

**Comment by PF4Public** [comment]
> so that we can re-open the issue

I would be very-very-very cautious about promising anything anyone, that's why I intentionally omitted this phrase ;) :D

**Comment by wchen342** [comment]
The it's better left out the entire sentence if there is no intention to do anything, otherwise it is confusing I think.

**Comment by PF4Public** [comment]
> there is no intention to do anything

Quite the opposite! If the information is sufficient for re-opening - why not! In case it is a mere "bump" thing — sorry, no way.

**Comment by wchen342** [comment]
> > there is no intention to do anything
> 
> Quite the opposite! If the information is sufficient for re-opening - why not! In case it is a mere "bump" thing — sorry, no way.

Without explanation I think people cannot read into all these in that one sentence, but let's keep it the way you put it for now.

**Review by networkException — APPROVED** [review]

**Pull request merged**
