### PR TITLE
Fix: code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
### Description
Hi :wave: I work at [DeepSource](https://deepsource.io), I ran DeepSource analysis on the forked copy of this repo and found some interesting [code quality issues](https://deepsource.io/gh/withshubh/ungoogled-chromium/issues/?category=recommended) in the codebase, opening this PR so you can assess if our platform is right and helpful for you.

### Summary of changes

- Use literal syntax instead of function calls to create data structure
- Use `sys.exit()` calls
- Remove unnecessary generator
- Refactor unnecessary `else` / `elif` when `if` block has a `raise` statement
- Remove implicit `object` from the base class
- Added .deepsource.toml config file to continuously analyze the repo

### CODE REVIEW

**Review by Eloston — APPROVED** [review]
This is pretty neat! Thanks for bringing this to my attention and fixing some problems.

**Comment by withshubh** [comment]
Hi @Eloston :wave: 

I'd like to get your feedback on DeepSource :sparkles: 

Using DeepSource to continuously analyze your repository for code quality issues:
- This repo already has the configuration file required to configure analysis settings.
- Install DeepSource on your repository [here](https://deepsource.io/signup).
- Activate analysis [here](https://deepsource.io/gh/Eloston/ungoogled-chromium/).

**Comment by Eloston** [comment]
Hi @withshubh 

Nothing much to report. So far the integration with GitHub has been smooth, and DeepSource has a nice UX overall. I especially like the detailed explanations for each of its suggestions; keep it up!

This project is a bit unusual compared to other software projects because its main component are patches on another code base (Chromium) instead of typical source code files. There is some Python tooling that's been built up over the years, but they are to support the patches and do not have a lot of active development. So I wouldn't expect much exciting feedback on Deep Source from this project.

That being said, I am looking to to applying Deep Source to more traditional software projects where I can. I believe there is a lot of potential in static analysis tooling, and more sophisticated development tooling in general. Looking forward to seeing where you guys take this!

**Comment by withshubh** [comment]
Thank You so much for your feedback @Eloston :sparkling_heart: 

We are constantly working to make DeepSource better.

**Pull request merged**
