### PR TITLE
avatar -> avatar/people/profile

### PR DESCRIPTION
**Pull request by PF4Public**
Reference: #1126

### CODE REVIEW

**Comment by qvint** [comment]
As per the project objective №2 (see the README),
I believe we should use the upstream terminology and be consistent with the existing flags.

----

**Comment by PF4Public** [comment]
> I believe we should use the upstream terminology and be consistent with the existing flags.

And answer the same questions again and again due to a poor wording choices made upstream? @Eloston himself couldn't find this flag!

**Comment by Eloston** [comment]
> @Eloston himself couldn't find this flag!

To be fair, I was being negligent and rushing things.

Anyway, I think @qvint makes a good point. Could you change the description to instead show "avatar/user button"? This has the additional benefit of working with `chrome://flags`'s "Search flags" function when you search "avatar".

**Comment by PF4Public** [comment]
Should it be then `Show avatar / user account button` or `Show avatar / user button`?

**Comment by Eloston** [comment]
Actually, I noticed that `chrome://settings` and the avatar menu calls profiles "people", not "users". So maybe we should call it `Show avatar/person button`? Or maybe `Show avatar/people/profile button` since the support docs still use the term "profile" (https://support.google.com/chrome/answer/2364824)?

([At one point it was called "user"](https://www.chromium.org/user-experience/multi-profiles), but I don't see that term used to describe the current iteration of the profile button)

**Comment by PF4Public** [comment]
As funny as it gets 🤣

**Pull request merged**
