### PR TITLE
Upgrade to Chromium 81.0.4044.122

### PR DESCRIPTION
**Pull request by Zoraver**
Chromium 81.0.4044.122 fixes 8 security issues. I will let you know once I have a successful build.

### CODE REVIEW

**Comment by Zoraver** [comment]
My build succeeded; feel free to merge.

**Comment by 23rd** [comment]
I'm not sure, but why are there so many lines with a whitespace at the end?

**Comment by Zoraver** [comment]
@23rd `quilt refresh` does that sometimes. If @Eloston prefers not to have it, I believe that adding `--strip-trailing-whitespace` to `QUILT_REFRESH_ARGS` should prevent it from happening.

**Comment by PF4Public** [comment]
Gentoo builds also succeeded: https://github.com/PF4Public/ungoogled-chromium-bin/releases/tag/81.0.4044.122-1

**Pull request merged**
